<?php
			$optionsArray = array( 'fields' => array( 'gridFields' => array(  ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array(  ) ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array( 'logo',
'menu',
'username_button' ),
'top' => array( 'breadcrumb',
'loginform_login' ),
'above-grid' => array( 'rights_save',
'rights_reset',
'rights_displaying_tables',
'rights_ordering_tables',
'rights_add_group',
'rights_del_group',
'rights_rename_group',
'rights_copy_permissions' ),
'below-grid' => array(  ),
'grid' => array( 'rights_search',
'rights_name_a',
'rights_name_e',
'rights_name_d',
'rights_name_s',
'rights_name_p',
'rights_name_i',
'rights_name_m',
'rights_checkbox_page',
'rights_page',
'rights_checkbox_page_a',
'rights_checkbox_page_e',
'rights_checkbox_page_d',
'rights_checkbox_page_s',
'rights_checkbox_page_p',
'rights_checkbox_page_i',
'rights_expand_all',
'rights_checkbox_all_a',
'rights_checkbox_all_e',
'rights_checkbox_all_d',
'rights_checkbox_all_s',
'rights_checkbox_all_p',
'rights_checkbox_all_i',
'rights_checkbox_all_m',
'rights_checkbox_table',
'rights_table',
'rights_show_pages',
'rights_hide_pages',
'rights_group_expander',
'rights_checkbox_a',
'rights_checkbox_e',
'rights_checkbox_d',
'rights_checkbox_s',
'rights_checkbox_p',
'rights_checkbox_i',
'rights_checkbox_m' ) ),
'formXtTags' => array( 'top' => array( 'breadcrumb',
'guestloginbutton' ),
'below-grid' => array(  ) ),
'itemForms' => array( 'logo' => 'supertop',
'menu' => 'supertop',
'username_button' => 'supertop',
'breadcrumb' => 'top',
'loginform_login' => 'top',
'rights_save' => 'above-grid',
'rights_reset' => 'above-grid',
'rights_displaying_tables' => 'above-grid',
'rights_ordering_tables' => 'above-grid',
'rights_add_group' => 'above-grid',
'rights_del_group' => 'above-grid',
'rights_rename_group' => 'above-grid',
'rights_copy_permissions' => 'above-grid',
'rights_search' => 'grid',
'rights_name_a' => 'grid',
'rights_name_e' => 'grid',
'rights_name_d' => 'grid',
'rights_name_s' => 'grid',
'rights_name_p' => 'grid',
'rights_name_i' => 'grid',
'rights_name_m' => 'grid',
'rights_checkbox_page' => 'grid',
'rights_page' => 'grid',
'rights_checkbox_page_a' => 'grid',
'rights_checkbox_page_e' => 'grid',
'rights_checkbox_page_d' => 'grid',
'rights_checkbox_page_s' => 'grid',
'rights_checkbox_page_p' => 'grid',
'rights_checkbox_page_i' => 'grid',
'rights_expand_all' => 'grid',
'rights_checkbox_all_a' => 'grid',
'rights_checkbox_all_e' => 'grid',
'rights_checkbox_all_d' => 'grid',
'rights_checkbox_all_s' => 'grid',
'rights_checkbox_all_p' => 'grid',
'rights_checkbox_all_i' => 'grid',
'rights_checkbox_all_m' => 'grid',
'rights_checkbox_table' => 'grid',
'rights_table' => 'grid',
'rights_show_pages' => 'grid',
'rights_hide_pages' => 'grid',
'rights_group_expander' => 'grid',
'rights_checkbox_a' => 'grid',
'rights_checkbox_e' => 'grid',
'rights_checkbox_d' => 'grid',
'rights_checkbox_s' => 'grid',
'rights_checkbox_p' => 'grid',
'rights_checkbox_i' => 'grid',
'rights_checkbox_m' => 'grid' ),
'itemLocations' => array(  ),
'itemVisiblity' => array( 'menu' => 3,
'username_button' => 3,
'loginform_login' => 3 ) ),
'itemsByType' => array( 'rights_save' => array( 'rights_save' ),
'rights_reset' => array( 'rights_reset' ),
'rights_add_group' => array( 'rights_add_group' ),
'rights_del_group' => array( 'rights_del_group' ),
'rights_rename_group' => array( 'rights_rename_group' ),
'rights_copy_permissions' => array( 'rights_copy_permissions' ),
'rights_displaying_tables' => array( 'rights_displaying_tables' ),
'rights_ordering_tables' => array( 'rights_ordering_tables' ),
'rights_search' => array( 'rights_search' ),
'rights_name_a' => array( 'rights_name_a' ),
'rights_name_e' => array( 'rights_name_e' ),
'rights_name_d' => array( 'rights_name_d' ),
'rights_name_s' => array( 'rights_name_s' ),
'rights_name_p' => array( 'rights_name_p' ),
'rights_name_i' => array( 'rights_name_i' ),
'rights_name_m' => array( 'rights_name_m' ),
'rights_checkbox_all_a' => array( 'rights_checkbox_all_a' ),
'rights_checkbox_all_e' => array( 'rights_checkbox_all_e' ),
'rights_checkbox_all_d' => array( 'rights_checkbox_all_d' ),
'rights_checkbox_all_s' => array( 'rights_checkbox_all_s' ),
'rights_checkbox_all_p' => array( 'rights_checkbox_all_p' ),
'rights_checkbox_all_i' => array( 'rights_checkbox_all_i' ),
'rights_checkbox_all_m' => array( 'rights_checkbox_all_m' ),
'rights_checkbox_table' => array( 'rights_checkbox_table' ),
'rights_table' => array( 'rights_table' ),
'rights_checkbox_a' => array( 'rights_checkbox_a' ),
'rights_checkbox_e' => array( 'rights_checkbox_e' ),
'rights_checkbox_d' => array( 'rights_checkbox_d' ),
'rights_checkbox_s' => array( 'rights_checkbox_s' ),
'rights_checkbox_p' => array( 'rights_checkbox_p' ),
'rights_checkbox_i' => array( 'rights_checkbox_i' ),
'rights_checkbox_m' => array( 'rights_checkbox_m' ),
'rights_page' => array( 'rights_page' ),
'rights_checkbox_page_a' => array( 'rights_checkbox_page_a' ),
'rights_checkbox_page_e' => array( 'rights_checkbox_page_e' ),
'rights_checkbox_page_d' => array( 'rights_checkbox_page_d' ),
'rights_checkbox_page_s' => array( 'rights_checkbox_page_s' ),
'rights_checkbox_page_p' => array( 'rights_checkbox_page_p' ),
'rights_checkbox_page_i' => array( 'rights_checkbox_page_i' ),
'rights_show_pages' => array( 'rights_show_pages' ),
'rights_hide_pages' => array( 'rights_hide_pages' ),
'rights_checkbox_page' => array( 'rights_checkbox_page' ),
'rights_group_expander' => array( 'rights_group_expander' ),
'rights_expand_all' => array( 'rights_expand_all' ),
'breadcrumb' => array( 'breadcrumb' ),
'logo' => array( 'logo' ),
'menu' => array( 'menu' ),
'loginform_login' => array( 'loginform_login' ),
'username_button' => array( 'username_button' ),
'logout_link' => array( 'logout_link' ),
'exit_adminarea_link' => array( 'exit_adminarea_link' ) ),
'cellMaps' => array(  ) ),
'page' => array( 'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ) );
			$pageArray = array( 'id' => 'admin_rights_list',
'type' => 'admin_rights_list',
'layoutId' => 'topbar',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'admin-topbar-menu',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'logo',
'menu' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c2' => array( 'model' => 'c2',
'items' => array( 'username_button' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'admin-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'breadcrumb',
'loginform_login' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'above-grid' => array( 'modelId' => 'admin-rights-above-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ),
array( 'cells' => array( array( 'cell' => 'c3' ),
array( 'cell' => 'c4' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'rights_save',
'rights_reset' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c2' => array( 'model' => 'c2',
'items' => array( 'rights_displaying_tables',
'rights_ordering_tables' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c3' => array( 'model' => 'c3',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c4' => array( 'model' => 'c4',
'items' => array( 'rights_add_group',
'rights_del_group',
'rights_rename_group',
'rights_copy_permissions' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'below-grid' => array( 'modelId' => 'admin-header',
'grid' => array(  ),
'cells' => array(  ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'admin-rights-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'headcell_search' ),
array( 'cell' => 'headcell_a' ),
array( 'cell' => 'headcell_e' ),
array( 'cell' => 'headcell_d' ),
array( 'cell' => 'headcell_s' ),
array( 'cell' => 'headcell_p' ),
array( 'cell' => 'headcell_i' ),
array( 'cell' => 'headcell_m' ) ),
'section' => 'head' ),
array( 'cells' => array( array( 'cell' => 'headcell_expand' ),
array( 'cell' => 'headcell_all_a' ),
array( 'cell' => 'headcell_all_e' ),
array( 'cell' => 'headcell_all_d' ),
array( 'cell' => 'headcell_all_s' ),
array( 'cell' => 'headcell_all_p' ),
array( 'cell' => 'headcell_all_i' ),
array( 'cell' => 'headcell_all_m' ) ),
'section' => 'head' ),
array( 'cells' => array( array( 'cell' => 'cell_table' ),
array( 'cell' => 'cell_a' ),
array( 'cell' => 'cell_e' ),
array( 'cell' => 'cell_d' ),
array( 'cell' => 'cell_s' ),
array( 'cell' => 'cell_p' ),
array( 'cell' => 'cell_i' ),
array( 'cell' => 'cell_m' ) ),
'section' => 'body' ),
array( 'cells' => array( array( 'cell' => 'cell_page' ),
array( 'cell' => 'cell_page_a' ),
array( 'cell' => 'cell_page_e' ),
array( 'cell' => 'cell_page_d' ),
array( 'cell' => 'cell_page_s' ),
array( 'cell' => 'cell_page_p' ),
array( 'cell' => 'cell_page_i' ),
array( 'cell' => 'cell_page_m' ) ),
'section' => 'page' ) ),
'cells' => array( 'headcell_search' => array( 'model' => 'headcell_search',
'items' => array( 'rights_search' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'headcell_a' => array( 'model' => 'headcell_a',
'items' => array( 'rights_name_a' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'headcell_e' => array( 'model' => 'headcell_e',
'items' => array( 'rights_name_e' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'headcell_d' => array( 'model' => 'headcell_d',
'items' => array( 'rights_name_d' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'headcell_s' => array( 'model' => 'headcell_s',
'items' => array( 'rights_name_s' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'headcell_p' => array( 'model' => 'headcell_p',
'items' => array( 'rights_name_p' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'headcell_i' => array( 'model' => 'headcell_i',
'items' => array( 'rights_name_i' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'headcell_m' => array( 'model' => 'headcell_m',
'items' => array( 'rights_name_m' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'cell_page' => array( 'model' => 'cell_page',
'items' => array( 'rights_checkbox_page',
'rights_page' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'cell_page_a' => array( 'model' => 'cell_page_a',
'items' => array( 'rights_checkbox_page_a' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0,
'permission' => 'A' ),
'cell_page_e' => array( 'model' => 'cell_page_e',
'items' => array( 'rights_checkbox_page_e' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0,
'permission' => 'E' ),
'cell_page_d' => array( 'model' => 'cell_page_d',
'items' => array( 'rights_checkbox_page_d' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0,
'permission' => 'D' ),
'cell_page_s' => array( 'model' => 'cell_page_s',
'items' => array( 'rights_checkbox_page_s' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0,
'permission' => 'S' ),
'cell_page_p' => array( 'model' => 'cell_page_p',
'items' => array( 'rights_checkbox_page_p' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0,
'permission' => 'P' ),
'cell_page_i' => array( 'model' => 'cell_page_i',
'items' => array( 'rights_checkbox_page_i' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0,
'permission' => 'I' ),
'cell_page_m' => array( 'model' => 'cell_page_m',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'headcell_expand' => array( 'model' => 'headcell_expand',
'items' => array( 'rights_expand_all' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'headcell_all_a' => array( 'model' => 'headcell_all_a',
'items' => array( 'rights_checkbox_all_a' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0,
'permission' => 'A' ),
'headcell_all_e' => array( 'model' => 'headcell_all_e',
'items' => array( 'rights_checkbox_all_e' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0,
'permission' => 'E' ),
'headcell_all_d' => array( 'model' => 'headcell_all_d',
'items' => array( 'rights_checkbox_all_d' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0,
'permission' => 'D' ),
'headcell_all_s' => array( 'model' => 'headcell_all_s',
'items' => array( 'rights_checkbox_all_s' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0,
'permission' => 'S' ),
'headcell_all_p' => array( 'model' => 'headcell_all_p',
'items' => array( 'rights_checkbox_all_p' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0,
'permission' => 'P' ),
'headcell_all_i' => array( 'model' => 'headcell_all_i',
'items' => array( 'rights_checkbox_all_i' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0,
'permission' => 'I' ),
'headcell_all_m' => array( 'model' => 'headcell_all_m',
'items' => array( 'rights_checkbox_all_m' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0,
'permission' => 'M' ),
'cell_table' => array( 'model' => 'cell_table',
'items' => array( 'rights_checkbox_table',
'rights_table',
'rights_show_pages',
'rights_hide_pages',
'rights_group_expander' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'cell_a' => array( 'model' => 'cell_a',
'items' => array( 'rights_checkbox_a' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0,
'permission' => 'A' ),
'cell_e' => array( 'model' => 'cell_e',
'items' => array( 'rights_checkbox_e' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0,
'permission' => 'E' ),
'cell_d' => array( 'model' => 'cell_d',
'items' => array( 'rights_checkbox_d' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0,
'permission' => 'D' ),
'cell_s' => array( 'model' => 'cell_s',
'items' => array( 'rights_checkbox_s' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0,
'permission' => 'S' ),
'cell_p' => array( 'model' => 'cell_p',
'items' => array( 'rights_checkbox_p' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0,
'permission' => 'P' ),
'cell_i' => array( 'model' => 'cell_i',
'items' => array( 'rights_checkbox_i' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0,
'permission' => 'I' ),
'cell_m' => array( 'model' => 'cell_m',
'items' => array( 'rights_checkbox_m' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0,
'permission' => 'M' ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'rights_save' => array( 'type' => 'rights_save' ),
'rights_reset' => array( 'type' => 'rights_reset' ),
'rights_add_group' => array( 'type' => 'rights_add_group' ),
'rights_del_group' => array( 'type' => 'rights_del_group' ),
'rights_rename_group' => array( 'type' => 'rights_rename_group' ),
'rights_copy_permissions' => array( 'type' => 'rights_copy_permissions' ),
'rights_displaying_tables' => array( 'type' => 'rights_displaying_tables' ),
'rights_ordering_tables' => array( 'type' => 'rights_ordering_tables' ),
'rights_search' => array( 'type' => 'rights_search' ),
'rights_name_a' => array( 'type' => 'rights_name_a' ),
'rights_name_e' => array( 'type' => 'rights_name_e' ),
'rights_name_d' => array( 'type' => 'rights_name_d' ),
'rights_name_s' => array( 'type' => 'rights_name_s' ),
'rights_name_p' => array( 'type' => 'rights_name_p' ),
'rights_name_i' => array( 'type' => 'rights_name_i' ),
'rights_name_m' => array( 'type' => 'rights_name_m' ),
'rights_checkbox_all_a' => array( 'type' => 'rights_checkbox_all_a' ),
'rights_checkbox_all_e' => array( 'type' => 'rights_checkbox_all_e' ),
'rights_checkbox_all_d' => array( 'type' => 'rights_checkbox_all_d' ),
'rights_checkbox_all_s' => array( 'type' => 'rights_checkbox_all_s' ),
'rights_checkbox_all_p' => array( 'type' => 'rights_checkbox_all_p' ),
'rights_checkbox_all_i' => array( 'type' => 'rights_checkbox_all_i' ),
'rights_checkbox_all_m' => array( 'type' => 'rights_checkbox_all_m' ),
'rights_checkbox_table' => array( 'type' => 'rights_checkbox_table' ),
'rights_table' => array( 'type' => 'rights_table' ),
'rights_checkbox_a' => array( 'type' => 'rights_checkbox_a' ),
'rights_checkbox_e' => array( 'type' => 'rights_checkbox_e' ),
'rights_checkbox_d' => array( 'type' => 'rights_checkbox_d' ),
'rights_checkbox_s' => array( 'type' => 'rights_checkbox_s' ),
'rights_checkbox_p' => array( 'type' => 'rights_checkbox_p' ),
'rights_checkbox_i' => array( 'type' => 'rights_checkbox_i' ),
'rights_checkbox_m' => array( 'type' => 'rights_checkbox_m' ),
'rights_page' => array( 'type' => 'rights_page' ),
'rights_checkbox_page_a' => array( 'type' => 'rights_checkbox_page_a' ),
'rights_checkbox_page_e' => array( 'type' => 'rights_checkbox_page_e' ),
'rights_checkbox_page_d' => array( 'type' => 'rights_checkbox_page_d' ),
'rights_checkbox_page_s' => array( 'type' => 'rights_checkbox_page_s' ),
'rights_checkbox_page_p' => array( 'type' => 'rights_checkbox_page_p' ),
'rights_checkbox_page_i' => array( 'type' => 'rights_checkbox_page_i' ),
'rights_show_pages' => array( 'type' => 'rights_show_pages' ),
'rights_hide_pages' => array( 'type' => 'rights_hide_pages' ),
'rights_checkbox_page' => array( 'type' => 'rights_checkbox_page' ),
'rights_group_expander' => array( 'type' => 'rights_group_expander' ),
'rights_expand_all' => array( 'type' => 'rights_expand_all' ),
'breadcrumb' => array( 'type' => 'breadcrumb' ),
'logo' => array( 'type' => 'logo' ),
'menu' => array( 'type' => 'menu' ),
'loginform_login' => array( 'type' => 'loginform_login' ),
'username_button' => array( 'type' => 'username_button',
'items' => array( 'logout_link',
'exit_adminarea_link' ) ),
'logout_link' => array( 'type' => 'logout_link' ),
'exit_adminarea_link' => array( 'type' => 'exit_adminarea_link' ) ),
'dbProps' => array(  ),
'version' => 4 );
		?>