<?php
			$optionsArray = array( 'captcha' => array( 'captcha' => false ),
'fields' => array( 'gridFields' => array( 'tanggaldaftar',
'nomap',
'namalengkap',
'jeniskelamin',
'nisn',
'nik',
'tempatlahir',
'tanggallahir1',
'noaktalahir',
'agama',
'alamatjalan',
'rt',
'rw',
'dusun',
'deskel',
'kecamatan',
'kodepos',
'tempattinggal',
'modatransportasi',
'anakke',
'namaayah',
'nikayah',
'tanggallahir2',
'pendidikan1',
'pekerjaan1',
'penghasilan1',
'statusayah',
'statusibu',
'nikibu',
'tanggallahir3',
'pendidikan2',
'pekerjaan2',
'penghasilan2',
'namawali',
'nikwali',
'tanggallahir4',
'pendidikan3',
'pekerjaan3',
'penghasilan3',
'kontak',
'nomorwa',
'tinggibadan',
'beratbadan',
'jaraktempatkesekolah',
'jumlahsaudarakandung',
'asaltk',
'nomorsurattk',
'paktaintegritas',
'namaibu' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'tanggaldaftar' => array( 'integrated_edit_field' ),
'nomap' => array( 'integrated_edit_field1' ),
'namalengkap' => array( 'integrated_edit_field2' ),
'jeniskelamin' => array( 'integrated_edit_field3' ),
'nisn' => array( 'integrated_edit_field4' ),
'nik' => array( 'integrated_edit_field5' ),
'tempatlahir' => array( 'integrated_edit_field6' ),
'tanggallahir1' => array( 'integrated_edit_field7' ),
'noaktalahir' => array( 'integrated_edit_field8' ),
'agama' => array( 'integrated_edit_field9' ),
'alamatjalan' => array( 'integrated_edit_field10' ),
'rt' => array( 'integrated_edit_field11' ),
'rw' => array( 'integrated_edit_field12' ),
'dusun' => array( 'integrated_edit_field13' ),
'deskel' => array( 'integrated_edit_field14' ),
'kecamatan' => array( 'integrated_edit_field15' ),
'kodepos' => array( 'integrated_edit_field16' ),
'tempattinggal' => array( 'integrated_edit_field17' ),
'modatransportasi' => array( 'integrated_edit_field18' ),
'anakke' => array( 'integrated_edit_field19' ),
'namaayah' => array( 'integrated_edit_field20' ),
'nikayah' => array( 'integrated_edit_field21' ),
'tanggallahir2' => array( 'integrated_edit_field22' ),
'pendidikan1' => array( 'integrated_edit_field23' ),
'pekerjaan1' => array( 'integrated_edit_field24' ),
'penghasilan1' => array( 'integrated_edit_field25' ),
'statusayah' => array( 'integrated_edit_field26' ),
'statusibu' => array( 'integrated_edit_field27' ),
'nikibu' => array( 'integrated_edit_field28' ),
'tanggallahir3' => array( 'integrated_edit_field29' ),
'pendidikan2' => array( 'integrated_edit_field30' ),
'pekerjaan2' => array( 'integrated_edit_field31' ),
'penghasilan2' => array( 'integrated_edit_field32' ),
'namawali' => array( 'integrated_edit_field33' ),
'nikwali' => array( 'integrated_edit_field34' ),
'tanggallahir4' => array( 'integrated_edit_field35' ),
'pendidikan3' => array( 'integrated_edit_field36' ),
'pekerjaan3' => array( 'integrated_edit_field37' ),
'penghasilan3' => array( 'integrated_edit_field38' ),
'kontak' => array( 'integrated_edit_field39' ),
'nomorwa' => array( 'integrated_edit_field40' ),
'tinggibadan' => array( 'integrated_edit_field42' ),
'beratbadan' => array( 'integrated_edit_field43' ),
'jaraktempatkesekolah' => array( 'integrated_edit_field44' ),
'jumlahsaudarakandung' => array( 'integrated_edit_field45' ),
'asaltk' => array( 'integrated_edit_field46' ),
'nomorsurattk' => array( 'integrated_edit_field47' ),
'paktaintegritas' => array( 'integrated_edit_field48' ),
'namaibu' => array( 'integrated_edit_field41' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'top' => array( 'add_header' ),
'above-grid' => array( 'add_message',
'text1',
'text' ),
'below-grid' => array( 'add_save',
'add_cancel',
'add_back_list' ),
'grid' => array( 'integrated_edit_field',
'integrated_edit_field1',
'section7',
'section6',
'section4',
'section3',
'section2',
'section1',
'section' ),
'section' => array( 'text2',
'integrated_edit_field48',
'text3' ),
'section1' => array( 'integrated_edit_field33',
'integrated_edit_field34',
'integrated_edit_field35',
'integrated_edit_field36',
'integrated_edit_field37',
'integrated_edit_field38' ),
'section2' => array( 'integrated_edit_field27',
'integrated_edit_field41',
'integrated_edit_field28',
'integrated_edit_field29',
'integrated_edit_field30',
'integrated_edit_field31',
'integrated_edit_field32',
'integrated_edit_field40' ),
'section3' => array( 'integrated_edit_field26',
'integrated_edit_field20',
'integrated_edit_field21',
'integrated_edit_field22',
'integrated_edit_field23',
'integrated_edit_field24',
'integrated_edit_field25',
'integrated_edit_field39' ),
'section4' => array( 'integrated_edit_field18',
'integrated_edit_field42',
'integrated_edit_field43',
'integrated_edit_field44',
'integrated_edit_field19',
'integrated_edit_field45',
'integrated_edit_field46',
'integrated_edit_field47' ),
'section6' => array( 'integrated_edit_field17',
'integrated_edit_field10',
'integrated_edit_field11',
'integrated_edit_field12',
'integrated_edit_field13',
'integrated_edit_field14',
'integrated_edit_field15',
'integrated_edit_field16' ),
'section7' => array( 'integrated_edit_field2',
'integrated_edit_field3',
'integrated_edit_field4',
'integrated_edit_field5',
'integrated_edit_field6',
'integrated_edit_field7',
'integrated_edit_field8',
'integrated_edit_field9' ) ),
'formXtTags' => array(  ),
'itemForms' => array( 'add_header' => 'top',
'add_message' => 'above-grid',
'text1' => 'above-grid',
'text' => 'above-grid',
'add_save' => 'below-grid',
'add_cancel' => 'below-grid',
'add_back_list' => 'below-grid',
'integrated_edit_field' => 'grid',
'integrated_edit_field1' => 'grid',
'section7' => 'grid',
'section6' => 'grid',
'section4' => 'grid',
'section3' => 'grid',
'section2' => 'grid',
'section1' => 'grid',
'section' => 'grid',
'text2' => 'section',
'integrated_edit_field48' => 'section',
'text3' => 'section',
'integrated_edit_field33' => 'section1',
'integrated_edit_field34' => 'section1',
'integrated_edit_field35' => 'section1',
'integrated_edit_field36' => 'section1',
'integrated_edit_field37' => 'section1',
'integrated_edit_field38' => 'section1',
'integrated_edit_field27' => 'section2',
'integrated_edit_field41' => 'section2',
'integrated_edit_field28' => 'section2',
'integrated_edit_field29' => 'section2',
'integrated_edit_field30' => 'section2',
'integrated_edit_field31' => 'section2',
'integrated_edit_field32' => 'section2',
'integrated_edit_field40' => 'section2',
'integrated_edit_field26' => 'section3',
'integrated_edit_field20' => 'section3',
'integrated_edit_field21' => 'section3',
'integrated_edit_field22' => 'section3',
'integrated_edit_field23' => 'section3',
'integrated_edit_field24' => 'section3',
'integrated_edit_field25' => 'section3',
'integrated_edit_field39' => 'section3',
'integrated_edit_field18' => 'section4',
'integrated_edit_field42' => 'section4',
'integrated_edit_field43' => 'section4',
'integrated_edit_field44' => 'section4',
'integrated_edit_field19' => 'section4',
'integrated_edit_field45' => 'section4',
'integrated_edit_field46' => 'section4',
'integrated_edit_field47' => 'section4',
'integrated_edit_field17' => 'section6',
'integrated_edit_field10' => 'section6',
'integrated_edit_field11' => 'section6',
'integrated_edit_field12' => 'section6',
'integrated_edit_field13' => 'section6',
'integrated_edit_field14' => 'section6',
'integrated_edit_field15' => 'section6',
'integrated_edit_field16' => 'section6',
'integrated_edit_field2' => 'section7',
'integrated_edit_field3' => 'section7',
'integrated_edit_field4' => 'section7',
'integrated_edit_field5' => 'section7',
'integrated_edit_field6' => 'section7',
'integrated_edit_field7' => 'section7',
'integrated_edit_field8' => 'section7',
'integrated_edit_field9' => 'section7' ),
'itemLocations' => array( 'integrated_edit_field' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field1' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'section7' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'section6' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'section4' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'section3' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'section2' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'section1' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'section' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'text2' => array( 'location' => 'section',
'cellId' => 'c1' ),
'integrated_edit_field48' => array( 'location' => 'section',
'cellId' => 'c1' ),
'text3' => array( 'location' => 'section',
'cellId' => 'c1' ),
'integrated_edit_field33' => array( 'location' => 'section1',
'cellId' => 'c1' ),
'integrated_edit_field34' => array( 'location' => 'section1',
'cellId' => 'c1' ),
'integrated_edit_field35' => array( 'location' => 'section1',
'cellId' => 'c1' ),
'integrated_edit_field36' => array( 'location' => 'section1',
'cellId' => 'c1' ),
'integrated_edit_field37' => array( 'location' => 'section1',
'cellId' => 'c1' ),
'integrated_edit_field38' => array( 'location' => 'section1',
'cellId' => 'c1' ),
'integrated_edit_field27' => array( 'location' => 'section2',
'cellId' => 'c1' ),
'integrated_edit_field41' => array( 'location' => 'section2',
'cellId' => 'c1' ),
'integrated_edit_field28' => array( 'location' => 'section2',
'cellId' => 'c1' ),
'integrated_edit_field29' => array( 'location' => 'section2',
'cellId' => 'c1' ),
'integrated_edit_field30' => array( 'location' => 'section2',
'cellId' => 'c1' ),
'integrated_edit_field31' => array( 'location' => 'section2',
'cellId' => 'c1' ),
'integrated_edit_field32' => array( 'location' => 'section2',
'cellId' => 'c1' ),
'integrated_edit_field40' => array( 'location' => 'section2',
'cellId' => 'c1' ),
'integrated_edit_field26' => array( 'location' => 'section3',
'cellId' => 'c1' ),
'integrated_edit_field20' => array( 'location' => 'section3',
'cellId' => 'c1' ),
'integrated_edit_field21' => array( 'location' => 'section3',
'cellId' => 'c1' ),
'integrated_edit_field22' => array( 'location' => 'section3',
'cellId' => 'c1' ),
'integrated_edit_field23' => array( 'location' => 'section3',
'cellId' => 'c1' ),
'integrated_edit_field24' => array( 'location' => 'section3',
'cellId' => 'c1' ),
'integrated_edit_field25' => array( 'location' => 'section3',
'cellId' => 'c1' ),
'integrated_edit_field39' => array( 'location' => 'section3',
'cellId' => 'c1' ),
'integrated_edit_field18' => array( 'location' => 'section4',
'cellId' => 'c1' ),
'integrated_edit_field42' => array( 'location' => 'section4',
'cellId' => 'c1' ),
'integrated_edit_field43' => array( 'location' => 'section4',
'cellId' => 'c1' ),
'integrated_edit_field44' => array( 'location' => 'section4',
'cellId' => 'c1' ),
'integrated_edit_field19' => array( 'location' => 'section4',
'cellId' => 'c1' ),
'integrated_edit_field45' => array( 'location' => 'section4',
'cellId' => 'c1' ),
'integrated_edit_field46' => array( 'location' => 'section4',
'cellId' => 'c1' ),
'integrated_edit_field47' => array( 'location' => 'section4',
'cellId' => 'c1' ),
'integrated_edit_field17' => array( 'location' => 'section6',
'cellId' => 'c1' ),
'integrated_edit_field10' => array( 'location' => 'section6',
'cellId' => 'c1' ),
'integrated_edit_field11' => array( 'location' => 'section6',
'cellId' => 'c1' ),
'integrated_edit_field12' => array( 'location' => 'section6',
'cellId' => 'c1' ),
'integrated_edit_field13' => array( 'location' => 'section6',
'cellId' => 'c1' ),
'integrated_edit_field14' => array( 'location' => 'section6',
'cellId' => 'c1' ),
'integrated_edit_field15' => array( 'location' => 'section6',
'cellId' => 'c1' ),
'integrated_edit_field16' => array( 'location' => 'section6',
'cellId' => 'c1' ),
'integrated_edit_field2' => array( 'location' => 'section7',
'cellId' => 'c1' ),
'integrated_edit_field3' => array( 'location' => 'section7',
'cellId' => 'c1' ),
'integrated_edit_field4' => array( 'location' => 'section7',
'cellId' => 'c1' ),
'integrated_edit_field5' => array( 'location' => 'section7',
'cellId' => 'c1' ),
'integrated_edit_field6' => array( 'location' => 'section7',
'cellId' => 'c1' ),
'integrated_edit_field7' => array( 'location' => 'section7',
'cellId' => 'c1' ),
'integrated_edit_field8' => array( 'location' => 'section7',
'cellId' => 'c1' ),
'integrated_edit_field9' => array( 'location' => 'section7',
'cellId' => 'c1' ) ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'add_header' => array( 'add_header' ),
'add_back_list' => array( 'add_back_list' ),
'add_cancel' => array( 'add_cancel' ),
'add_message' => array( 'add_message' ),
'add_save' => array( 'add_save' ),
'integrated_edit_field' => array( 'integrated_edit_field',
'integrated_edit_field1',
'integrated_edit_field2',
'integrated_edit_field3',
'integrated_edit_field4',
'integrated_edit_field5',
'integrated_edit_field6',
'integrated_edit_field7',
'integrated_edit_field8',
'integrated_edit_field9',
'integrated_edit_field10',
'integrated_edit_field11',
'integrated_edit_field12',
'integrated_edit_field13',
'integrated_edit_field14',
'integrated_edit_field15',
'integrated_edit_field16',
'integrated_edit_field17',
'integrated_edit_field18',
'integrated_edit_field19',
'integrated_edit_field20',
'integrated_edit_field21',
'integrated_edit_field22',
'integrated_edit_field23',
'integrated_edit_field24',
'integrated_edit_field25',
'integrated_edit_field26',
'integrated_edit_field27',
'integrated_edit_field28',
'integrated_edit_field29',
'integrated_edit_field30',
'integrated_edit_field31',
'integrated_edit_field32',
'integrated_edit_field33',
'integrated_edit_field34',
'integrated_edit_field35',
'integrated_edit_field36',
'integrated_edit_field37',
'integrated_edit_field38',
'integrated_edit_field39',
'integrated_edit_field40',
'integrated_edit_field42',
'integrated_edit_field43',
'integrated_edit_field44',
'integrated_edit_field45',
'integrated_edit_field46',
'integrated_edit_field47',
'integrated_edit_field48',
'integrated_edit_field41' ),
'section' => array( 'section',
'section1',
'section2',
'section3',
'section4',
'section6',
'section7' ),
'text' => array( 'text',
'text1',
'text2',
'text3' ) ),
'cellMaps' => array( 'grid' => array( 'cells' => array( 'c3' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field',
'integrated_edit_field1',
'section7',
'section6',
'section4',
'section3',
'section2',
'section1',
'section' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 1,
'height' => 1 ),
'section' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'text2',
'integrated_edit_field48',
'text3' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 1,
'height' => 1 ),
'section1' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field33',
'integrated_edit_field34',
'integrated_edit_field35',
'integrated_edit_field36',
'integrated_edit_field37',
'integrated_edit_field38' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 1,
'height' => 1 ),
'section2' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field27',
'integrated_edit_field41',
'integrated_edit_field28',
'integrated_edit_field29',
'integrated_edit_field30',
'integrated_edit_field31',
'integrated_edit_field32',
'integrated_edit_field40' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 1,
'height' => 1 ),
'section3' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field26',
'integrated_edit_field20',
'integrated_edit_field21',
'integrated_edit_field22',
'integrated_edit_field23',
'integrated_edit_field24',
'integrated_edit_field25',
'integrated_edit_field39' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 1,
'height' => 1 ),
'section4' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field18',
'integrated_edit_field42',
'integrated_edit_field43',
'integrated_edit_field44',
'integrated_edit_field19',
'integrated_edit_field45',
'integrated_edit_field46',
'integrated_edit_field47' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 1,
'height' => 1 ),
'section6' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field17',
'integrated_edit_field10',
'integrated_edit_field11',
'integrated_edit_field12',
'integrated_edit_field13',
'integrated_edit_field14',
'integrated_edit_field15',
'integrated_edit_field16' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 1,
'height' => 1 ),
'section7' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field2',
'integrated_edit_field3',
'integrated_edit_field4',
'integrated_edit_field5',
'integrated_edit_field6',
'integrated_edit_field7',
'integrated_edit_field8',
'integrated_edit_field9' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 1,
'height' => 1 ) ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false ),
'misc' => array( 'type' => 'add',
'breadcrumb' => false ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ) );
			$pageArray = array( 'id' => 'add',
'type' => 'add',
'layoutId' => 'nomenu',
'disabled' => 0,
'default' => 0,
'forms' => array( 'top' => array( 'modelId' => 'add-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'add_header' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0,
'align' => 'center' ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'above-grid' => array( 'modelId' => 'add-above-grid',
'grid' => array( array( 'section' => '',
'cells' => array( array( 'cell' => 'c' ) ) ),
array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'add_message' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0,
'align' => 'center' ),
'c' => array( 'model' => 'c1',
'items' => array( 'text1',
'text' ),
'align' => 'center',
'nowrap' => false,
'background' => '#e8ff00' ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'below-grid' => array( 'modelId' => 'add-below-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c' ) ) ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'add_save',
'add_cancel' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c' => array( 'model' => 'c1',
'items' => array( 'add_back_list' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c3' ) ),
'section' => '' ) ),
'cells' => array( 'c3' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field',
'integrated_edit_field1',
'section7',
'section6',
'section4',
'section3',
'section2',
'section1',
'section' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0,
'align' => 'center' ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'text2',
'integrated_edit_field48',
'text3' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0,
'align' => 'center' ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section1' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field33',
'integrated_edit_field34',
'integrated_edit_field35',
'integrated_edit_field36',
'integrated_edit_field37',
'integrated_edit_field38' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section2' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field27',
'integrated_edit_field41',
'integrated_edit_field28',
'integrated_edit_field29',
'integrated_edit_field30',
'integrated_edit_field31',
'integrated_edit_field32',
'integrated_edit_field40' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section3' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field26',
'integrated_edit_field20',
'integrated_edit_field21',
'integrated_edit_field22',
'integrated_edit_field23',
'integrated_edit_field24',
'integrated_edit_field25',
'integrated_edit_field39' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section4' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field18',
'integrated_edit_field42',
'integrated_edit_field43',
'integrated_edit_field44',
'integrated_edit_field19',
'integrated_edit_field45',
'integrated_edit_field46',
'integrated_edit_field47' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section6' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field17',
'integrated_edit_field10',
'integrated_edit_field11',
'integrated_edit_field12',
'integrated_edit_field13',
'integrated_edit_field14',
'integrated_edit_field15',
'integrated_edit_field16' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section7' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field2',
'integrated_edit_field3',
'integrated_edit_field4',
'integrated_edit_field5',
'integrated_edit_field6',
'integrated_edit_field7',
'integrated_edit_field8',
'integrated_edit_field9' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ) ),
'items' => array( 'add_header' => array( 'type' => 'add_header',
'title' => array( 'page' => 'add',
'table' => 'calonppdb',
'type' => 7 ) ),
'add_back_list' => array( 'type' => 'add_back_list',
'label' => array( 'type' => 0,
'text' => 'Kembali ke Daftar Siswa PPDB' ),
'padding' => array( 'top' => '10px' ) ),
'add_cancel' => array( 'type' => 'add_cancel' ),
'add_message' => array( 'type' => 'add_message' ),
'add_save' => array( 'type' => 'add_save',
'label' => array( 'type' => 0,
'text' => 'Simpan Sekarang' ) ),
'integrated_edit_field' => array( 'field' => 'tanggaldaftar',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field1' => array( 'field' => 'nomap',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field2' => array( 'field' => 'namalengkap',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field3' => array( 'field' => 'jeniskelamin',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field4' => array( 'field' => 'nisn',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field5' => array( 'field' => 'nik',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field6' => array( 'field' => 'tempatlahir',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field7' => array( 'field' => 'tanggallahir1',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field8' => array( 'field' => 'noaktalahir',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field9' => array( 'field' => 'agama',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field10' => array( 'field' => 'alamatjalan',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field11' => array( 'field' => 'rt',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field12' => array( 'field' => 'rw',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field13' => array( 'field' => 'dusun',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field14' => array( 'field' => 'deskel',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field15' => array( 'field' => 'kecamatan',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field16' => array( 'field' => 'kodepos',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field17' => array( 'field' => 'tempattinggal',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field18' => array( 'field' => 'modatransportasi',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field19' => array( 'field' => 'anakke',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field20' => array( 'field' => 'namaayah',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field21' => array( 'field' => 'nikayah',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field22' => array( 'field' => 'tanggallahir2',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field23' => array( 'field' => 'pendidikan1',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field24' => array( 'field' => 'pekerjaan1',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field25' => array( 'field' => 'penghasilan1',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field26' => array( 'field' => 'statusayah',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field27' => array( 'field' => 'statusibu',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field28' => array( 'field' => 'nikibu',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field29' => array( 'field' => 'tanggallahir3',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field30' => array( 'field' => 'pendidikan2',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field31' => array( 'field' => 'pekerjaan2',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field32' => array( 'field' => 'penghasilan2',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field33' => array( 'field' => 'namawali',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field34' => array( 'field' => 'nikwali',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field35' => array( 'field' => 'tanggallahir4',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field36' => array( 'field' => 'pendidikan3',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field37' => array( 'field' => 'pekerjaan3',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field38' => array( 'field' => 'penghasilan3',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field39' => array( 'field' => 'kontak',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field40' => array( 'field' => 'nomorwa',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field42' => array( 'field' => 'tinggibadan',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field43' => array( 'field' => 'beratbadan',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field44' => array( 'field' => 'jaraktempatkesekolah',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field45' => array( 'field' => 'jumlahsaudarakandung',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field46' => array( 'field' => 'asaltk',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field47' => array( 'field' => 'nomorsurattk',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field48' => array( 'field' => 'paktaintegritas',
'type' => 'integrated_edit_field',
'orientation' => 0,
'mobileDisplay' => 'both' ),
'section' => array( 'type' => 'section',
'title' => array( 'text' => 'Pakta Integritas',
'type' => 0 ),
'location' => 'section',
'mobileDisplay' => 'both',
'initiallyClosed' => true ),
'section1' => array( 'type' => 'section',
'title' => array( 'text' => 'Data Wali (Jika Ada)',
'type' => 0 ),
'location' => 'section1',
'mobileDisplay' => 'both',
'initiallyClosed' => true ),
'section2' => array( 'type' => 'section',
'title' => array( 'text' => 'Data Ibu Kandung',
'type' => 0 ),
'location' => 'section2',
'mobileDisplay' => 'both',
'initiallyClosed' => true ),
'section3' => array( 'type' => 'section',
'title' => array( 'text' => 'Data Ayah Kandung',
'type' => 0 ),
'location' => 'section3',
'mobileDisplay' => 'both',
'initiallyClosed' => true ),
'section4' => array( 'type' => 'section',
'title' => array( 'text' => 'Data Turunan Siswa',
'type' => 0 ),
'location' => 'section4',
'mobileDisplay' => 'both',
'initiallyClosed' => true ),
'section6' => array( 'type' => 'section',
'title' => array( 'text' => 'Alamat Siswa',
'type' => 0 ),
'location' => 'section6',
'mobileDisplay' => 'both',
'initiallyClosed' => true ),
'section7' => array( 'type' => 'section',
'title' => array( 'text' => 'Data Siswa',
'type' => 0 ),
'location' => 'section7',
'mobileDisplay' => 'both',
'initiallyClosed' => true ),
'integrated_edit_field41' => array( 'field' => 'namaibu',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'text' => array( 'type' => 'text',
'label' => array( 'text' => 'Untuk mengurangi kesalahan input dalam pengisian Formulir Online dibawah ini. Pastikan Anda telah mengisi Formulir PPDB 2022 terlebih dahulu pada MAP PPDB 2022',
'type' => 0 ),
'color' => '#0001ff',
'mobileDisplay' => 'both',
'nowrap' => false,
'bold' => true,
'font-size' => '16px',
'padding' => array( 'top' => '5px' ) ),
'text1' => array( 'type' => 'text',
'label' => array( 'text' => 'PERHATIAN !!!',
'type' => 0 ),
'mobileDisplay' => 'both',
'color' => '#c90000',
'font-size' => '18px',
'bold' => true ),
'text2' => array( 'type' => 'text',
'label' => array( 'text' => 'Saya yang bertanda tangan dibawah ini, dengan sadar dan sebenar-benarnya data yang saya isikan pada Formulir Pendaftaran Online PPDB 2022 NAMA SEKOLAH adalah BENAR dan saya siap menerima resiko yang ditimbulkan atas kesalahan isian pada form ini. Sesuai kebijaksanaan Panitia PPDB NAMA SEKOLAH.',
'type' => 0 ),
'nowrap' => false,
'mobileDisplay' => 'both',
'bold' => true,
'font-size' => '14px' ),
'text3' => array( 'type' => 'text',
'label' => array( 'text' => '(Kotak Tanda Tangan Digital)',
'type' => 0 ),
'mobileDisplay' => 'both',
'nowrap' => false,
'italic' => true,
'color' => '#de0b0b' ) ),
'dbProps' => array(  ),
'version' => 4 );
		?>