<?php
			$optionsArray = array( 'fields' => array( 'gridFields' => array( 'ID',
'tanggaldaftar',
'nomap',
'namalengkap',
'jeniskelamin',
'nisn',
'nik',
'tempatlahir',
'tanggallahir1',
'noaktalahir',
'agama',
'alamatjalan',
'rt',
'rw',
'dusun',
'deskel',
'kecamatan',
'kodepos',
'tempattinggal',
'modatransportasi',
'anakke',
'namaayah',
'nikayah',
'tanggallahir2',
'pendidikan1',
'pekerjaan1',
'penghasilan1',
'statusayah',
'statusibu',
'nikibu',
'tanggallahir3',
'pendidikan2',
'pekerjaan2',
'penghasilan2',
'namawali',
'nikwali',
'tanggallahir4',
'pendidikan3',
'pekerjaan3',
'penghasilan3',
'kontak',
'nomorwa',
'email',
'tinggibadan',
'beratbadan',
'jaraktempatkesekolah',
'jumlahsaudarakandung',
'asaltk',
'nomorsurattk',
'paktaintegritas',
'namaibu',
'status' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'ID' => array( 'import_field' ),
'tanggaldaftar' => array( 'import_field1' ),
'nomap' => array( 'import_field2' ),
'namalengkap' => array( 'import_field3' ),
'jeniskelamin' => array( 'import_field4' ),
'nisn' => array( 'import_field5' ),
'nik' => array( 'import_field6' ),
'tempatlahir' => array( 'import_field7' ),
'tanggallahir1' => array( 'import_field8' ),
'noaktalahir' => array( 'import_field9' ),
'agama' => array( 'import_field10' ),
'alamatjalan' => array( 'import_field11' ),
'rt' => array( 'import_field12' ),
'rw' => array( 'import_field13' ),
'dusun' => array( 'import_field14' ),
'deskel' => array( 'import_field15' ),
'kecamatan' => array( 'import_field16' ),
'kodepos' => array( 'import_field17' ),
'tempattinggal' => array( 'import_field18' ),
'modatransportasi' => array( 'import_field19' ),
'anakke' => array( 'import_field20' ),
'namaayah' => array( 'import_field21' ),
'nikayah' => array( 'import_field22' ),
'tanggallahir2' => array( 'import_field23' ),
'pendidikan1' => array( 'import_field24' ),
'pekerjaan1' => array( 'import_field25' ),
'penghasilan1' => array( 'import_field26' ),
'statusayah' => array( 'import_field27' ),
'statusibu' => array( 'import_field28' ),
'nikibu' => array( 'import_field29' ),
'tanggallahir3' => array( 'import_field30' ),
'pendidikan2' => array( 'import_field31' ),
'pekerjaan2' => array( 'import_field32' ),
'penghasilan2' => array( 'import_field33' ),
'namawali' => array( 'import_field34' ),
'nikwali' => array( 'import_field35' ),
'tanggallahir4' => array( 'import_field36' ),
'pendidikan3' => array( 'import_field37' ),
'pekerjaan3' => array( 'import_field38' ),
'penghasilan3' => array( 'import_field39' ),
'kontak' => array( 'import_field40' ),
'nomorwa' => array( 'import_field41' ),
'email' => array( 'import_field42' ),
'tinggibadan' => array( 'import_field43' ),
'beratbadan' => array( 'import_field44' ),
'jaraktempatkesekolah' => array( 'import_field45' ),
'jumlahsaudarakandung' => array( 'import_field46' ),
'asaltk' => array( 'import_field47' ),
'nomorsurattk' => array( 'import_field48' ),
'paktaintegritas' => array( 'import_field49' ),
'namaibu' => array( 'import_field50' ),
'status' => array( 'import_field51' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'import_header' ),
'grid' => array( 'import_field',
'import_field1',
'import_field2',
'import_field3',
'import_field4',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field10',
'import_field11',
'import_field12',
'import_field13',
'import_field14',
'import_field15',
'import_field16',
'import_field17',
'import_field18',
'import_field19',
'import_field20',
'import_field21',
'import_field22',
'import_field23',
'import_field24',
'import_field25',
'import_field26',
'import_field27',
'import_field28',
'import_field29',
'import_field30',
'import_field31',
'import_field32',
'import_field33',
'import_field34',
'import_field35',
'import_field36',
'import_field37',
'import_field38',
'import_field39',
'import_field40',
'import_field41',
'import_field42',
'import_field43',
'import_field44',
'import_field45',
'import_field46',
'import_field47',
'import_field48',
'import_field49',
'import_field50',
'import_field51' ) ),
'formXtTags' => array( 'supertop' => array(  ) ),
'itemForms' => array( 'import_header' => 'top',
'import_field' => 'grid',
'import_field1' => 'grid',
'import_field2' => 'grid',
'import_field3' => 'grid',
'import_field4' => 'grid',
'import_field5' => 'grid',
'import_field6' => 'grid',
'import_field7' => 'grid',
'import_field8' => 'grid',
'import_field9' => 'grid',
'import_field10' => 'grid',
'import_field11' => 'grid',
'import_field12' => 'grid',
'import_field13' => 'grid',
'import_field14' => 'grid',
'import_field15' => 'grid',
'import_field16' => 'grid',
'import_field17' => 'grid',
'import_field18' => 'grid',
'import_field19' => 'grid',
'import_field20' => 'grid',
'import_field21' => 'grid',
'import_field22' => 'grid',
'import_field23' => 'grid',
'import_field24' => 'grid',
'import_field25' => 'grid',
'import_field26' => 'grid',
'import_field27' => 'grid',
'import_field28' => 'grid',
'import_field29' => 'grid',
'import_field30' => 'grid',
'import_field31' => 'grid',
'import_field32' => 'grid',
'import_field33' => 'grid',
'import_field34' => 'grid',
'import_field35' => 'grid',
'import_field36' => 'grid',
'import_field37' => 'grid',
'import_field38' => 'grid',
'import_field39' => 'grid',
'import_field40' => 'grid',
'import_field41' => 'grid',
'import_field42' => 'grid',
'import_field43' => 'grid',
'import_field44' => 'grid',
'import_field45' => 'grid',
'import_field46' => 'grid',
'import_field47' => 'grid',
'import_field48' => 'grid',
'import_field49' => 'grid',
'import_field50' => 'grid',
'import_field51' => 'grid' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'import_header' => array( 'import_header' ),
'import_field' => array( 'import_field',
'import_field1',
'import_field2',
'import_field3',
'import_field4',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field10',
'import_field11',
'import_field12',
'import_field13',
'import_field14',
'import_field15',
'import_field16',
'import_field17',
'import_field18',
'import_field19',
'import_field20',
'import_field21',
'import_field22',
'import_field23',
'import_field24',
'import_field25',
'import_field26',
'import_field27',
'import_field28',
'import_field29',
'import_field30',
'import_field31',
'import_field32',
'import_field33',
'import_field34',
'import_field35',
'import_field36',
'import_field37',
'import_field38',
'import_field39',
'import_field40',
'import_field41',
'import_field42',
'import_field43',
'import_field44',
'import_field45',
'import_field46',
'import_field47',
'import_field48',
'import_field49',
'import_field50',
'import_field51' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ) );
			$pageArray = array( 'id' => 'import',
'type' => 'import',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'import-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'import_header' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'import-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'import_field',
'import_field1',
'import_field2',
'import_field3',
'import_field4',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field10',
'import_field11',
'import_field12',
'import_field13',
'import_field14',
'import_field15',
'import_field16',
'import_field17',
'import_field18',
'import_field19',
'import_field20',
'import_field21',
'import_field22',
'import_field23',
'import_field24',
'import_field25',
'import_field26',
'import_field27',
'import_field28',
'import_field29',
'import_field30',
'import_field31',
'import_field32',
'import_field33',
'import_field34',
'import_field35',
'import_field36',
'import_field37',
'import_field38',
'import_field39',
'import_field40',
'import_field41',
'import_field42',
'import_field43',
'import_field44',
'import_field45',
'import_field46',
'import_field47',
'import_field48',
'import_field49',
'import_field50',
'import_field51' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'import_header' => array( 'type' => 'import_header' ),
'import_field' => array( 'field' => 'ID',
'type' => 'import_field' ),
'import_field1' => array( 'field' => 'tanggaldaftar',
'type' => 'import_field' ),
'import_field2' => array( 'field' => 'nomap',
'type' => 'import_field' ),
'import_field3' => array( 'field' => 'namalengkap',
'type' => 'import_field' ),
'import_field4' => array( 'field' => 'jeniskelamin',
'type' => 'import_field' ),
'import_field5' => array( 'field' => 'nisn',
'type' => 'import_field' ),
'import_field6' => array( 'field' => 'nik',
'type' => 'import_field' ),
'import_field7' => array( 'field' => 'tempatlahir',
'type' => 'import_field' ),
'import_field8' => array( 'field' => 'tanggallahir1',
'type' => 'import_field' ),
'import_field9' => array( 'field' => 'noaktalahir',
'type' => 'import_field' ),
'import_field10' => array( 'field' => 'agama',
'type' => 'import_field' ),
'import_field11' => array( 'field' => 'alamatjalan',
'type' => 'import_field' ),
'import_field12' => array( 'field' => 'rt',
'type' => 'import_field' ),
'import_field13' => array( 'field' => 'rw',
'type' => 'import_field' ),
'import_field14' => array( 'field' => 'dusun',
'type' => 'import_field' ),
'import_field15' => array( 'field' => 'deskel',
'type' => 'import_field' ),
'import_field16' => array( 'field' => 'kecamatan',
'type' => 'import_field' ),
'import_field17' => array( 'field' => 'kodepos',
'type' => 'import_field' ),
'import_field18' => array( 'field' => 'tempattinggal',
'type' => 'import_field' ),
'import_field19' => array( 'field' => 'modatransportasi',
'type' => 'import_field' ),
'import_field20' => array( 'field' => 'anakke',
'type' => 'import_field' ),
'import_field21' => array( 'field' => 'namaayah',
'type' => 'import_field' ),
'import_field22' => array( 'field' => 'nikayah',
'type' => 'import_field' ),
'import_field23' => array( 'field' => 'tanggallahir2',
'type' => 'import_field' ),
'import_field24' => array( 'field' => 'pendidikan1',
'type' => 'import_field' ),
'import_field25' => array( 'field' => 'pekerjaan1',
'type' => 'import_field' ),
'import_field26' => array( 'field' => 'penghasilan1',
'type' => 'import_field' ),
'import_field27' => array( 'field' => 'statusayah',
'type' => 'import_field' ),
'import_field28' => array( 'field' => 'statusibu',
'type' => 'import_field' ),
'import_field29' => array( 'field' => 'nikibu',
'type' => 'import_field' ),
'import_field30' => array( 'field' => 'tanggallahir3',
'type' => 'import_field' ),
'import_field31' => array( 'field' => 'pendidikan2',
'type' => 'import_field' ),
'import_field32' => array( 'field' => 'pekerjaan2',
'type' => 'import_field' ),
'import_field33' => array( 'field' => 'penghasilan2',
'type' => 'import_field' ),
'import_field34' => array( 'field' => 'namawali',
'type' => 'import_field' ),
'import_field35' => array( 'field' => 'nikwali',
'type' => 'import_field' ),
'import_field36' => array( 'field' => 'tanggallahir4',
'type' => 'import_field' ),
'import_field37' => array( 'field' => 'pendidikan3',
'type' => 'import_field' ),
'import_field38' => array( 'field' => 'pekerjaan3',
'type' => 'import_field' ),
'import_field39' => array( 'field' => 'penghasilan3',
'type' => 'import_field' ),
'import_field40' => array( 'field' => 'kontak',
'type' => 'import_field' ),
'import_field41' => array( 'field' => 'nomorwa',
'type' => 'import_field' ),
'import_field42' => array( 'field' => 'email',
'type' => 'import_field' ),
'import_field43' => array( 'field' => 'tinggibadan',
'type' => 'import_field' ),
'import_field44' => array( 'field' => 'beratbadan',
'type' => 'import_field' ),
'import_field45' => array( 'field' => 'jaraktempatkesekolah',
'type' => 'import_field' ),
'import_field46' => array( 'field' => 'jumlahsaudarakandung',
'type' => 'import_field' ),
'import_field47' => array( 'field' => 'asaltk',
'type' => 'import_field' ),
'import_field48' => array( 'field' => 'nomorsurattk',
'type' => 'import_field' ),
'import_field49' => array( 'field' => 'paktaintegritas',
'type' => 'import_field' ),
'import_field50' => array( 'field' => 'namaibu',
'type' => 'import_field' ),
'import_field51' => array( 'field' => 'status',
'type' => 'import_field' ) ),
'dbProps' => array(  ),
'version' => 4 );
		?>