<?php
			$optionsArray = array( 'pdf' => array( 'pdfView' => false ),
'totals' => array( 'ID' => array( 'totalsType' => '' ),
'tanggaldaftar' => array( 'totalsType' => '' ),
'nomap' => array( 'totalsType' => '' ),
'namalengkap' => array( 'totalsType' => '' ),
'jeniskelamin' => array( 'totalsType' => '' ),
'nisn' => array( 'totalsType' => '' ),
'nik' => array( 'totalsType' => '' ),
'tempatlahir' => array( 'totalsType' => '' ),
'tanggallahir1' => array( 'totalsType' => '' ),
'noaktalahir' => array( 'totalsType' => '' ),
'agama' => array( 'totalsType' => '' ),
'alamatjalan' => array( 'totalsType' => '' ),
'rt' => array( 'totalsType' => '' ),
'rw' => array( 'totalsType' => '' ),
'dusun' => array( 'totalsType' => '' ),
'deskel' => array( 'totalsType' => '' ),
'kecamatan' => array( 'totalsType' => '' ),
'kodepos' => array( 'totalsType' => '' ),
'tempattinggal' => array( 'totalsType' => '' ),
'modatransportasi' => array( 'totalsType' => '' ),
'anakke' => array( 'totalsType' => '' ),
'namaayah' => array( 'totalsType' => '' ),
'nikayah' => array( 'totalsType' => '' ),
'tanggallahir2' => array( 'totalsType' => '' ),
'pendidikan1' => array( 'totalsType' => '' ),
'pekerjaan1' => array( 'totalsType' => '' ),
'penghasilan1' => array( 'totalsType' => '' ),
'statusayah' => array( 'totalsType' => '' ),
'statusibu' => array( 'totalsType' => '' ),
'nikibu' => array( 'totalsType' => '' ),
'tanggallahir3' => array( 'totalsType' => '' ),
'pendidikan2' => array( 'totalsType' => '' ),
'pekerjaan2' => array( 'totalsType' => '' ),
'penghasilan2' => array( 'totalsType' => '' ),
'namawali' => array( 'totalsType' => '' ),
'nikwali' => array( 'totalsType' => '' ),
'tanggallahir4' => array( 'totalsType' => '' ),
'pendidikan3' => array( 'totalsType' => '' ),
'pekerjaan3' => array( 'totalsType' => '' ),
'penghasilan3' => array( 'totalsType' => '' ),
'kontak' => array( 'totalsType' => '' ),
'nomorwa' => array( 'totalsType' => '' ),
'email' => array( 'totalsType' => '' ),
'tinggibadan' => array( 'totalsType' => '' ),
'beratbadan' => array( 'totalsType' => '' ),
'jaraktempatkesekolah' => array( 'totalsType' => '' ),
'jumlahsaudarakandung' => array( 'totalsType' => '' ),
'asaltk' => array( 'totalsType' => '' ),
'nomorsurattk' => array( 'totalsType' => '' ),
'paktaintegritas' => array( 'totalsType' => '' ),
'namaibu' => array( 'totalsType' => '' ),
'status' => array( 'totalsType' => '' ) ),
'fields' => array( 'gridFields' => array( 'ID',
'tanggaldaftar',
'nomap',
'namalengkap',
'jeniskelamin',
'nisn',
'nik',
'tempatlahir',
'tanggallahir1',
'noaktalahir',
'agama',
'alamatjalan',
'rt',
'rw',
'dusun',
'deskel',
'kecamatan',
'kodepos',
'tempattinggal',
'modatransportasi',
'anakke',
'namaayah',
'nikayah',
'tanggallahir2',
'pendidikan1',
'pekerjaan1',
'penghasilan1',
'statusayah',
'statusibu',
'nikibu',
'tanggallahir3',
'pendidikan2',
'pekerjaan2',
'penghasilan2',
'namawali',
'nikwali',
'tanggallahir4',
'pendidikan3',
'pekerjaan3',
'penghasilan3',
'kontak',
'nomorwa',
'email',
'tinggibadan',
'beratbadan',
'jaraktempatkesekolah',
'jumlahsaudarakandung',
'asaltk',
'nomorsurattk',
'paktaintegritas',
'namaibu',
'status' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'ID' => array( 'simple_grid_field',
'simple_grid_field52' ),
'tanggaldaftar' => array( 'simple_grid_field1',
'simple_grid_field53' ),
'nomap' => array( 'simple_grid_field2',
'simple_grid_field54' ),
'namalengkap' => array( 'simple_grid_field3',
'simple_grid_field55' ),
'jeniskelamin' => array( 'simple_grid_field4',
'simple_grid_field56' ),
'nisn' => array( 'simple_grid_field5',
'simple_grid_field57' ),
'nik' => array( 'simple_grid_field6',
'simple_grid_field58' ),
'tempatlahir' => array( 'simple_grid_field7',
'simple_grid_field59' ),
'tanggallahir1' => array( 'simple_grid_field8',
'simple_grid_field60' ),
'noaktalahir' => array( 'simple_grid_field9',
'simple_grid_field61' ),
'agama' => array( 'simple_grid_field10',
'simple_grid_field62' ),
'alamatjalan' => array( 'simple_grid_field11',
'simple_grid_field63' ),
'rt' => array( 'simple_grid_field12',
'simple_grid_field64' ),
'rw' => array( 'simple_grid_field13',
'simple_grid_field65' ),
'dusun' => array( 'simple_grid_field14',
'simple_grid_field66' ),
'deskel' => array( 'simple_grid_field15',
'simple_grid_field67' ),
'kecamatan' => array( 'simple_grid_field16',
'simple_grid_field68' ),
'kodepos' => array( 'simple_grid_field17',
'simple_grid_field69' ),
'tempattinggal' => array( 'simple_grid_field18',
'simple_grid_field70' ),
'modatransportasi' => array( 'simple_grid_field19',
'simple_grid_field71' ),
'anakke' => array( 'simple_grid_field20',
'simple_grid_field72' ),
'namaayah' => array( 'simple_grid_field21',
'simple_grid_field73' ),
'nikayah' => array( 'simple_grid_field22',
'simple_grid_field74' ),
'tanggallahir2' => array( 'simple_grid_field23',
'simple_grid_field75' ),
'pendidikan1' => array( 'simple_grid_field24',
'simple_grid_field76' ),
'pekerjaan1' => array( 'simple_grid_field25',
'simple_grid_field77' ),
'penghasilan1' => array( 'simple_grid_field26',
'simple_grid_field78' ),
'statusayah' => array( 'simple_grid_field27',
'simple_grid_field79' ),
'statusibu' => array( 'simple_grid_field28',
'simple_grid_field80' ),
'nikibu' => array( 'simple_grid_field29',
'simple_grid_field81' ),
'tanggallahir3' => array( 'simple_grid_field30',
'simple_grid_field82' ),
'pendidikan2' => array( 'simple_grid_field31',
'simple_grid_field83' ),
'pekerjaan2' => array( 'simple_grid_field32',
'simple_grid_field84' ),
'penghasilan2' => array( 'simple_grid_field33',
'simple_grid_field85' ),
'namawali' => array( 'simple_grid_field34',
'simple_grid_field86' ),
'nikwali' => array( 'simple_grid_field35',
'simple_grid_field87' ),
'tanggallahir4' => array( 'simple_grid_field36',
'simple_grid_field88' ),
'pendidikan3' => array( 'simple_grid_field37',
'simple_grid_field89' ),
'pekerjaan3' => array( 'simple_grid_field38',
'simple_grid_field90' ),
'penghasilan3' => array( 'simple_grid_field39',
'simple_grid_field91' ),
'kontak' => array( 'simple_grid_field40',
'simple_grid_field92' ),
'nomorwa' => array( 'simple_grid_field41',
'simple_grid_field93' ),
'email' => array( 'simple_grid_field42',
'simple_grid_field94' ),
'tinggibadan' => array( 'simple_grid_field43',
'simple_grid_field95' ),
'beratbadan' => array( 'simple_grid_field44',
'simple_grid_field96' ),
'jaraktempatkesekolah' => array( 'simple_grid_field45',
'simple_grid_field97' ),
'jumlahsaudarakandung' => array( 'simple_grid_field46',
'simple_grid_field98' ),
'asaltk' => array( 'simple_grid_field47',
'simple_grid_field99' ),
'nomorsurattk' => array( 'simple_grid_field48',
'simple_grid_field100' ),
'paktaintegritas' => array( 'simple_grid_field49',
'simple_grid_field101' ),
'namaibu' => array( 'simple_grid_field50',
'simple_grid_field102' ),
'status' => array( 'simple_grid_field51',
'simple_grid_field103' ) ),
'hideEmptyFields' => array(  ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'top' => array( 'print_header',
'print_subheader' ),
'above-grid' => array( 'print_pages' ),
'below-grid' => array(  ),
'grid' => array( 'simple_grid_field52',
'simple_grid_field',
'simple_grid_field53',
'simple_grid_field1',
'simple_grid_field54',
'simple_grid_field2',
'simple_grid_field55',
'simple_grid_field3',
'simple_grid_field56',
'simple_grid_field4',
'simple_grid_field57',
'simple_grid_field5',
'simple_grid_field58',
'simple_grid_field6',
'simple_grid_field59',
'simple_grid_field7',
'simple_grid_field60',
'simple_grid_field8',
'simple_grid_field61',
'simple_grid_field9',
'simple_grid_field62',
'simple_grid_field10',
'simple_grid_field63',
'simple_grid_field11',
'simple_grid_field64',
'simple_grid_field12',
'simple_grid_field65',
'simple_grid_field13',
'simple_grid_field66',
'simple_grid_field14',
'simple_grid_field67',
'simple_grid_field15',
'simple_grid_field68',
'simple_grid_field16',
'simple_grid_field69',
'simple_grid_field17',
'simple_grid_field70',
'simple_grid_field18',
'simple_grid_field71',
'simple_grid_field19',
'simple_grid_field72',
'simple_grid_field20',
'simple_grid_field73',
'simple_grid_field21',
'simple_grid_field74',
'simple_grid_field22',
'simple_grid_field75',
'simple_grid_field23',
'simple_grid_field76',
'simple_grid_field24',
'simple_grid_field77',
'simple_grid_field25',
'simple_grid_field78',
'simple_grid_field26',
'simple_grid_field79',
'simple_grid_field27',
'simple_grid_field80',
'simple_grid_field28',
'simple_grid_field81',
'simple_grid_field29',
'simple_grid_field82',
'simple_grid_field30',
'simple_grid_field83',
'simple_grid_field31',
'simple_grid_field84',
'simple_grid_field32',
'simple_grid_field85',
'simple_grid_field33',
'simple_grid_field86',
'simple_grid_field34',
'simple_grid_field87',
'simple_grid_field35',
'simple_grid_field88',
'simple_grid_field36',
'simple_grid_field89',
'simple_grid_field37',
'simple_grid_field90',
'simple_grid_field38',
'simple_grid_field91',
'simple_grid_field39',
'simple_grid_field92',
'simple_grid_field40',
'simple_grid_field93',
'simple_grid_field41',
'simple_grid_field94',
'simple_grid_field42',
'simple_grid_field95',
'simple_grid_field43',
'simple_grid_field96',
'simple_grid_field44',
'simple_grid_field97',
'simple_grid_field45',
'simple_grid_field98',
'simple_grid_field46',
'simple_grid_field99',
'simple_grid_field47',
'simple_grid_field100',
'simple_grid_field48',
'simple_grid_field101',
'simple_grid_field49',
'simple_grid_field102',
'simple_grid_field50',
'simple_grid_field103',
'simple_grid_field51' ) ),
'formXtTags' => array( 'above-grid' => array( 'print_pages' ),
'below-grid' => array(  ) ),
'itemForms' => array( 'print_header' => 'top',
'print_subheader' => 'top',
'print_pages' => 'above-grid',
'simple_grid_field52' => 'grid',
'simple_grid_field' => 'grid',
'simple_grid_field53' => 'grid',
'simple_grid_field1' => 'grid',
'simple_grid_field54' => 'grid',
'simple_grid_field2' => 'grid',
'simple_grid_field55' => 'grid',
'simple_grid_field3' => 'grid',
'simple_grid_field56' => 'grid',
'simple_grid_field4' => 'grid',
'simple_grid_field57' => 'grid',
'simple_grid_field5' => 'grid',
'simple_grid_field58' => 'grid',
'simple_grid_field6' => 'grid',
'simple_grid_field59' => 'grid',
'simple_grid_field7' => 'grid',
'simple_grid_field60' => 'grid',
'simple_grid_field8' => 'grid',
'simple_grid_field61' => 'grid',
'simple_grid_field9' => 'grid',
'simple_grid_field62' => 'grid',
'simple_grid_field10' => 'grid',
'simple_grid_field63' => 'grid',
'simple_grid_field11' => 'grid',
'simple_grid_field64' => 'grid',
'simple_grid_field12' => 'grid',
'simple_grid_field65' => 'grid',
'simple_grid_field13' => 'grid',
'simple_grid_field66' => 'grid',
'simple_grid_field14' => 'grid',
'simple_grid_field67' => 'grid',
'simple_grid_field15' => 'grid',
'simple_grid_field68' => 'grid',
'simple_grid_field16' => 'grid',
'simple_grid_field69' => 'grid',
'simple_grid_field17' => 'grid',
'simple_grid_field70' => 'grid',
'simple_grid_field18' => 'grid',
'simple_grid_field71' => 'grid',
'simple_grid_field19' => 'grid',
'simple_grid_field72' => 'grid',
'simple_grid_field20' => 'grid',
'simple_grid_field73' => 'grid',
'simple_grid_field21' => 'grid',
'simple_grid_field74' => 'grid',
'simple_grid_field22' => 'grid',
'simple_grid_field75' => 'grid',
'simple_grid_field23' => 'grid',
'simple_grid_field76' => 'grid',
'simple_grid_field24' => 'grid',
'simple_grid_field77' => 'grid',
'simple_grid_field25' => 'grid',
'simple_grid_field78' => 'grid',
'simple_grid_field26' => 'grid',
'simple_grid_field79' => 'grid',
'simple_grid_field27' => 'grid',
'simple_grid_field80' => 'grid',
'simple_grid_field28' => 'grid',
'simple_grid_field81' => 'grid',
'simple_grid_field29' => 'grid',
'simple_grid_field82' => 'grid',
'simple_grid_field30' => 'grid',
'simple_grid_field83' => 'grid',
'simple_grid_field31' => 'grid',
'simple_grid_field84' => 'grid',
'simple_grid_field32' => 'grid',
'simple_grid_field85' => 'grid',
'simple_grid_field33' => 'grid',
'simple_grid_field86' => 'grid',
'simple_grid_field34' => 'grid',
'simple_grid_field87' => 'grid',
'simple_grid_field35' => 'grid',
'simple_grid_field88' => 'grid',
'simple_grid_field36' => 'grid',
'simple_grid_field89' => 'grid',
'simple_grid_field37' => 'grid',
'simple_grid_field90' => 'grid',
'simple_grid_field38' => 'grid',
'simple_grid_field91' => 'grid',
'simple_grid_field39' => 'grid',
'simple_grid_field92' => 'grid',
'simple_grid_field40' => 'grid',
'simple_grid_field93' => 'grid',
'simple_grid_field41' => 'grid',
'simple_grid_field94' => 'grid',
'simple_grid_field42' => 'grid',
'simple_grid_field95' => 'grid',
'simple_grid_field43' => 'grid',
'simple_grid_field96' => 'grid',
'simple_grid_field44' => 'grid',
'simple_grid_field97' => 'grid',
'simple_grid_field45' => 'grid',
'simple_grid_field98' => 'grid',
'simple_grid_field46' => 'grid',
'simple_grid_field99' => 'grid',
'simple_grid_field47' => 'grid',
'simple_grid_field100' => 'grid',
'simple_grid_field48' => 'grid',
'simple_grid_field101' => 'grid',
'simple_grid_field49' => 'grid',
'simple_grid_field102' => 'grid',
'simple_grid_field50' => 'grid',
'simple_grid_field103' => 'grid',
'simple_grid_field51' => 'grid' ),
'itemLocations' => array( 'simple_grid_field52' => array( 'location' => 'grid',
'cellId' => 'headcell_field' ),
'simple_grid_field' => array( 'location' => 'grid',
'cellId' => 'cell_field' ),
'simple_grid_field53' => array( 'location' => 'grid',
'cellId' => 'headcell_field1' ),
'simple_grid_field1' => array( 'location' => 'grid',
'cellId' => 'cell_field1' ),
'simple_grid_field54' => array( 'location' => 'grid',
'cellId' => 'headcell_field2' ),
'simple_grid_field2' => array( 'location' => 'grid',
'cellId' => 'cell_field2' ),
'simple_grid_field55' => array( 'location' => 'grid',
'cellId' => 'headcell_field3' ),
'simple_grid_field3' => array( 'location' => 'grid',
'cellId' => 'cell_field3' ),
'simple_grid_field56' => array( 'location' => 'grid',
'cellId' => 'headcell_field4' ),
'simple_grid_field4' => array( 'location' => 'grid',
'cellId' => 'cell_field4' ),
'simple_grid_field57' => array( 'location' => 'grid',
'cellId' => 'headcell_field5' ),
'simple_grid_field5' => array( 'location' => 'grid',
'cellId' => 'cell_field5' ),
'simple_grid_field58' => array( 'location' => 'grid',
'cellId' => 'headcell_field6' ),
'simple_grid_field6' => array( 'location' => 'grid',
'cellId' => 'cell_field6' ),
'simple_grid_field59' => array( 'location' => 'grid',
'cellId' => 'headcell_field7' ),
'simple_grid_field7' => array( 'location' => 'grid',
'cellId' => 'cell_field7' ),
'simple_grid_field60' => array( 'location' => 'grid',
'cellId' => 'headcell_field8' ),
'simple_grid_field8' => array( 'location' => 'grid',
'cellId' => 'cell_field8' ),
'simple_grid_field61' => array( 'location' => 'grid',
'cellId' => 'headcell_field9' ),
'simple_grid_field9' => array( 'location' => 'grid',
'cellId' => 'cell_field9' ),
'simple_grid_field62' => array( 'location' => 'grid',
'cellId' => 'headcell_field10' ),
'simple_grid_field10' => array( 'location' => 'grid',
'cellId' => 'cell_field10' ),
'simple_grid_field63' => array( 'location' => 'grid',
'cellId' => 'headcell_field11' ),
'simple_grid_field11' => array( 'location' => 'grid',
'cellId' => 'cell_field11' ),
'simple_grid_field64' => array( 'location' => 'grid',
'cellId' => 'headcell_field12' ),
'simple_grid_field12' => array( 'location' => 'grid',
'cellId' => 'cell_field12' ),
'simple_grid_field65' => array( 'location' => 'grid',
'cellId' => 'headcell_field13' ),
'simple_grid_field13' => array( 'location' => 'grid',
'cellId' => 'cell_field13' ),
'simple_grid_field66' => array( 'location' => 'grid',
'cellId' => 'headcell_field14' ),
'simple_grid_field14' => array( 'location' => 'grid',
'cellId' => 'cell_field14' ),
'simple_grid_field67' => array( 'location' => 'grid',
'cellId' => 'headcell_field15' ),
'simple_grid_field15' => array( 'location' => 'grid',
'cellId' => 'cell_field15' ),
'simple_grid_field68' => array( 'location' => 'grid',
'cellId' => 'headcell_field16' ),
'simple_grid_field16' => array( 'location' => 'grid',
'cellId' => 'cell_field16' ),
'simple_grid_field69' => array( 'location' => 'grid',
'cellId' => 'headcell_field17' ),
'simple_grid_field17' => array( 'location' => 'grid',
'cellId' => 'cell_field17' ),
'simple_grid_field70' => array( 'location' => 'grid',
'cellId' => 'headcell_field18' ),
'simple_grid_field18' => array( 'location' => 'grid',
'cellId' => 'cell_field18' ),
'simple_grid_field71' => array( 'location' => 'grid',
'cellId' => 'headcell_field19' ),
'simple_grid_field19' => array( 'location' => 'grid',
'cellId' => 'cell_field19' ),
'simple_grid_field72' => array( 'location' => 'grid',
'cellId' => 'headcell_field20' ),
'simple_grid_field20' => array( 'location' => 'grid',
'cellId' => 'cell_field20' ),
'simple_grid_field73' => array( 'location' => 'grid',
'cellId' => 'headcell_field21' ),
'simple_grid_field21' => array( 'location' => 'grid',
'cellId' => 'cell_field21' ),
'simple_grid_field74' => array( 'location' => 'grid',
'cellId' => 'headcell_field22' ),
'simple_grid_field22' => array( 'location' => 'grid',
'cellId' => 'cell_field22' ),
'simple_grid_field75' => array( 'location' => 'grid',
'cellId' => 'headcell_field23' ),
'simple_grid_field23' => array( 'location' => 'grid',
'cellId' => 'cell_field23' ),
'simple_grid_field76' => array( 'location' => 'grid',
'cellId' => 'headcell_field24' ),
'simple_grid_field24' => array( 'location' => 'grid',
'cellId' => 'cell_field24' ),
'simple_grid_field77' => array( 'location' => 'grid',
'cellId' => 'headcell_field25' ),
'simple_grid_field25' => array( 'location' => 'grid',
'cellId' => 'cell_field25' ),
'simple_grid_field78' => array( 'location' => 'grid',
'cellId' => 'headcell_field26' ),
'simple_grid_field26' => array( 'location' => 'grid',
'cellId' => 'cell_field26' ),
'simple_grid_field79' => array( 'location' => 'grid',
'cellId' => 'headcell_field27' ),
'simple_grid_field27' => array( 'location' => 'grid',
'cellId' => 'cell_field27' ),
'simple_grid_field80' => array( 'location' => 'grid',
'cellId' => 'headcell_field28' ),
'simple_grid_field28' => array( 'location' => 'grid',
'cellId' => 'cell_field28' ),
'simple_grid_field81' => array( 'location' => 'grid',
'cellId' => 'headcell_field29' ),
'simple_grid_field29' => array( 'location' => 'grid',
'cellId' => 'cell_field29' ),
'simple_grid_field82' => array( 'location' => 'grid',
'cellId' => 'headcell_field30' ),
'simple_grid_field30' => array( 'location' => 'grid',
'cellId' => 'cell_field30' ),
'simple_grid_field83' => array( 'location' => 'grid',
'cellId' => 'headcell_field31' ),
'simple_grid_field31' => array( 'location' => 'grid',
'cellId' => 'cell_field31' ),
'simple_grid_field84' => array( 'location' => 'grid',
'cellId' => 'headcell_field32' ),
'simple_grid_field32' => array( 'location' => 'grid',
'cellId' => 'cell_field32' ),
'simple_grid_field85' => array( 'location' => 'grid',
'cellId' => 'headcell_field33' ),
'simple_grid_field33' => array( 'location' => 'grid',
'cellId' => 'cell_field33' ),
'simple_grid_field86' => array( 'location' => 'grid',
'cellId' => 'headcell_field34' ),
'simple_grid_field34' => array( 'location' => 'grid',
'cellId' => 'cell_field34' ),
'simple_grid_field87' => array( 'location' => 'grid',
'cellId' => 'headcell_field35' ),
'simple_grid_field35' => array( 'location' => 'grid',
'cellId' => 'cell_field35' ),
'simple_grid_field88' => array( 'location' => 'grid',
'cellId' => 'headcell_field36' ),
'simple_grid_field36' => array( 'location' => 'grid',
'cellId' => 'cell_field36' ),
'simple_grid_field89' => array( 'location' => 'grid',
'cellId' => 'headcell_field37' ),
'simple_grid_field37' => array( 'location' => 'grid',
'cellId' => 'cell_field37' ),
'simple_grid_field90' => array( 'location' => 'grid',
'cellId' => 'headcell_field38' ),
'simple_grid_field38' => array( 'location' => 'grid',
'cellId' => 'cell_field38' ),
'simple_grid_field91' => array( 'location' => 'grid',
'cellId' => 'headcell_field39' ),
'simple_grid_field39' => array( 'location' => 'grid',
'cellId' => 'cell_field39' ),
'simple_grid_field92' => array( 'location' => 'grid',
'cellId' => 'headcell_field40' ),
'simple_grid_field40' => array( 'location' => 'grid',
'cellId' => 'cell_field40' ),
'simple_grid_field93' => array( 'location' => 'grid',
'cellId' => 'headcell_field41' ),
'simple_grid_field41' => array( 'location' => 'grid',
'cellId' => 'cell_field41' ),
'simple_grid_field94' => array( 'location' => 'grid',
'cellId' => 'headcell_field42' ),
'simple_grid_field42' => array( 'location' => 'grid',
'cellId' => 'cell_field42' ),
'simple_grid_field95' => array( 'location' => 'grid',
'cellId' => 'headcell_field43' ),
'simple_grid_field43' => array( 'location' => 'grid',
'cellId' => 'cell_field43' ),
'simple_grid_field96' => array( 'location' => 'grid',
'cellId' => 'headcell_field44' ),
'simple_grid_field44' => array( 'location' => 'grid',
'cellId' => 'cell_field44' ),
'simple_grid_field97' => array( 'location' => 'grid',
'cellId' => 'headcell_field45' ),
'simple_grid_field45' => array( 'location' => 'grid',
'cellId' => 'cell_field45' ),
'simple_grid_field98' => array( 'location' => 'grid',
'cellId' => 'headcell_field46' ),
'simple_grid_field46' => array( 'location' => 'grid',
'cellId' => 'cell_field46' ),
'simple_grid_field99' => array( 'location' => 'grid',
'cellId' => 'headcell_field47' ),
'simple_grid_field47' => array( 'location' => 'grid',
'cellId' => 'cell_field47' ),
'simple_grid_field100' => array( 'location' => 'grid',
'cellId' => 'headcell_field48' ),
'simple_grid_field48' => array( 'location' => 'grid',
'cellId' => 'cell_field48' ),
'simple_grid_field101' => array( 'location' => 'grid',
'cellId' => 'headcell_field49' ),
'simple_grid_field49' => array( 'location' => 'grid',
'cellId' => 'cell_field49' ),
'simple_grid_field102' => array( 'location' => 'grid',
'cellId' => 'headcell_field50' ),
'simple_grid_field50' => array( 'location' => 'grid',
'cellId' => 'cell_field50' ),
'simple_grid_field103' => array( 'location' => 'grid',
'cellId' => 'headcell_field51' ),
'simple_grid_field51' => array( 'location' => 'grid',
'cellId' => 'cell_field51' ) ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'print_header' => array( 'print_header' ),
'print_subheader' => array( 'print_subheader' ),
'print_pages' => array( 'print_pages' ),
'grid_field' => array( 'simple_grid_field',
'simple_grid_field1',
'simple_grid_field2',
'simple_grid_field3',
'simple_grid_field4',
'simple_grid_field5',
'simple_grid_field6',
'simple_grid_field7',
'simple_grid_field8',
'simple_grid_field9',
'simple_grid_field10',
'simple_grid_field11',
'simple_grid_field12',
'simple_grid_field13',
'simple_grid_field14',
'simple_grid_field15',
'simple_grid_field16',
'simple_grid_field17',
'simple_grid_field18',
'simple_grid_field19',
'simple_grid_field20',
'simple_grid_field21',
'simple_grid_field22',
'simple_grid_field23',
'simple_grid_field24',
'simple_grid_field25',
'simple_grid_field26',
'simple_grid_field27',
'simple_grid_field28',
'simple_grid_field29',
'simple_grid_field30',
'simple_grid_field31',
'simple_grid_field32',
'simple_grid_field33',
'simple_grid_field34',
'simple_grid_field35',
'simple_grid_field36',
'simple_grid_field37',
'simple_grid_field38',
'simple_grid_field39',
'simple_grid_field40',
'simple_grid_field41',
'simple_grid_field42',
'simple_grid_field43',
'simple_grid_field44',
'simple_grid_field45',
'simple_grid_field46',
'simple_grid_field47',
'simple_grid_field48',
'simple_grid_field49',
'simple_grid_field50',
'simple_grid_field51' ),
'grid_field_label' => array( 'simple_grid_field52',
'simple_grid_field53',
'simple_grid_field54',
'simple_grid_field55',
'simple_grid_field56',
'simple_grid_field57',
'simple_grid_field58',
'simple_grid_field59',
'simple_grid_field60',
'simple_grid_field61',
'simple_grid_field62',
'simple_grid_field63',
'simple_grid_field64',
'simple_grid_field65',
'simple_grid_field66',
'simple_grid_field67',
'simple_grid_field68',
'simple_grid_field69',
'simple_grid_field70',
'simple_grid_field71',
'simple_grid_field72',
'simple_grid_field73',
'simple_grid_field74',
'simple_grid_field75',
'simple_grid_field76',
'simple_grid_field77',
'simple_grid_field78',
'simple_grid_field79',
'simple_grid_field80',
'simple_grid_field81',
'simple_grid_field82',
'simple_grid_field83',
'simple_grid_field84',
'simple_grid_field85',
'simple_grid_field86',
'simple_grid_field87',
'simple_grid_field88',
'simple_grid_field89',
'simple_grid_field90',
'simple_grid_field91',
'simple_grid_field92',
'simple_grid_field93',
'simple_grid_field94',
'simple_grid_field95',
'simple_grid_field96',
'simple_grid_field97',
'simple_grid_field98',
'simple_grid_field99',
'simple_grid_field100',
'simple_grid_field101',
'simple_grid_field102',
'simple_grid_field103' ) ),
'cellMaps' => array( 'grid' => array( 'cells' => array( 'headcell_field' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array( 'ID_fieldheadercolumn' ),
'items' => array( 'simple_grid_field52' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field1' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array( 'tanggaldaftar_fieldheadercolumn' ),
'items' => array( 'simple_grid_field53' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field2' => array( 'cols' => array( 2 ),
'rows' => array( 0 ),
'tags' => array( 'nomap_fieldheadercolumn' ),
'items' => array( 'simple_grid_field54' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field3' => array( 'cols' => array( 3 ),
'rows' => array( 0 ),
'tags' => array( 'namalengkap_fieldheadercolumn' ),
'items' => array( 'simple_grid_field55' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field4' => array( 'cols' => array( 4 ),
'rows' => array( 0 ),
'tags' => array( 'jeniskelamin_fieldheadercolumn' ),
'items' => array( 'simple_grid_field56' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field5' => array( 'cols' => array( 5 ),
'rows' => array( 0 ),
'tags' => array( 'nisn_fieldheadercolumn' ),
'items' => array( 'simple_grid_field57' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field6' => array( 'cols' => array( 6 ),
'rows' => array( 0 ),
'tags' => array( 'nik_fieldheadercolumn' ),
'items' => array( 'simple_grid_field58' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field7' => array( 'cols' => array( 7 ),
'rows' => array( 0 ),
'tags' => array( 'tempatlahir_fieldheadercolumn' ),
'items' => array( 'simple_grid_field59' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field8' => array( 'cols' => array( 8 ),
'rows' => array( 0 ),
'tags' => array( 'tanggallahir1_fieldheadercolumn' ),
'items' => array( 'simple_grid_field60' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field9' => array( 'cols' => array( 9 ),
'rows' => array( 0 ),
'tags' => array( 'noaktalahir_fieldheadercolumn' ),
'items' => array( 'simple_grid_field61' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field10' => array( 'cols' => array( 10 ),
'rows' => array( 0 ),
'tags' => array( 'agama_fieldheadercolumn' ),
'items' => array( 'simple_grid_field62' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field11' => array( 'cols' => array( 11 ),
'rows' => array( 0 ),
'tags' => array( 'alamatjalan_fieldheadercolumn' ),
'items' => array( 'simple_grid_field63' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field12' => array( 'cols' => array( 12 ),
'rows' => array( 0 ),
'tags' => array( 'rt_fieldheadercolumn' ),
'items' => array( 'simple_grid_field64' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field13' => array( 'cols' => array( 13 ),
'rows' => array( 0 ),
'tags' => array( 'rw_fieldheadercolumn' ),
'items' => array( 'simple_grid_field65' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field14' => array( 'cols' => array( 14 ),
'rows' => array( 0 ),
'tags' => array( 'dusun_fieldheadercolumn' ),
'items' => array( 'simple_grid_field66' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field15' => array( 'cols' => array( 15 ),
'rows' => array( 0 ),
'tags' => array( 'deskel_fieldheadercolumn' ),
'items' => array( 'simple_grid_field67' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field16' => array( 'cols' => array( 16 ),
'rows' => array( 0 ),
'tags' => array( 'kecamatan_fieldheadercolumn' ),
'items' => array( 'simple_grid_field68' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field17' => array( 'cols' => array( 17 ),
'rows' => array( 0 ),
'tags' => array( 'kodepos_fieldheadercolumn' ),
'items' => array( 'simple_grid_field69' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field18' => array( 'cols' => array( 18 ),
'rows' => array( 0 ),
'tags' => array( 'tempattinggal_fieldheadercolumn' ),
'items' => array( 'simple_grid_field70' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field19' => array( 'cols' => array( 19 ),
'rows' => array( 0 ),
'tags' => array( 'modatransportasi_fieldheadercolumn' ),
'items' => array( 'simple_grid_field71' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field20' => array( 'cols' => array( 20 ),
'rows' => array( 0 ),
'tags' => array( 'anakke_fieldheadercolumn' ),
'items' => array( 'simple_grid_field72' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field21' => array( 'cols' => array( 21 ),
'rows' => array( 0 ),
'tags' => array( 'namaayah_fieldheadercolumn' ),
'items' => array( 'simple_grid_field73' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field22' => array( 'cols' => array( 22 ),
'rows' => array( 0 ),
'tags' => array( 'nikayah_fieldheadercolumn' ),
'items' => array( 'simple_grid_field74' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field23' => array( 'cols' => array( 23 ),
'rows' => array( 0 ),
'tags' => array( 'tanggallahir2_fieldheadercolumn' ),
'items' => array( 'simple_grid_field75' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field24' => array( 'cols' => array( 24 ),
'rows' => array( 0 ),
'tags' => array( 'pendidikan1_fieldheadercolumn' ),
'items' => array( 'simple_grid_field76' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field25' => array( 'cols' => array( 25 ),
'rows' => array( 0 ),
'tags' => array( 'pekerjaan1_fieldheadercolumn' ),
'items' => array( 'simple_grid_field77' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field26' => array( 'cols' => array( 26 ),
'rows' => array( 0 ),
'tags' => array( 'penghasilan1_fieldheadercolumn' ),
'items' => array( 'simple_grid_field78' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field27' => array( 'cols' => array( 27 ),
'rows' => array( 0 ),
'tags' => array( 'statusayah_fieldheadercolumn' ),
'items' => array( 'simple_grid_field79' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field28' => array( 'cols' => array( 28 ),
'rows' => array( 0 ),
'tags' => array( 'statusibu_fieldheadercolumn' ),
'items' => array( 'simple_grid_field80' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field29' => array( 'cols' => array( 29 ),
'rows' => array( 0 ),
'tags' => array( 'nikibu_fieldheadercolumn' ),
'items' => array( 'simple_grid_field81' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field30' => array( 'cols' => array( 30 ),
'rows' => array( 0 ),
'tags' => array( 'tanggallahir3_fieldheadercolumn' ),
'items' => array( 'simple_grid_field82' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field31' => array( 'cols' => array( 31 ),
'rows' => array( 0 ),
'tags' => array( 'pendidikan2_fieldheadercolumn' ),
'items' => array( 'simple_grid_field83' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field32' => array( 'cols' => array( 32 ),
'rows' => array( 0 ),
'tags' => array( 'pekerjaan2_fieldheadercolumn' ),
'items' => array( 'simple_grid_field84' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field33' => array( 'cols' => array( 33 ),
'rows' => array( 0 ),
'tags' => array( 'penghasilan2_fieldheadercolumn' ),
'items' => array( 'simple_grid_field85' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field34' => array( 'cols' => array( 34 ),
'rows' => array( 0 ),
'tags' => array( 'namawali_fieldheadercolumn' ),
'items' => array( 'simple_grid_field86' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field35' => array( 'cols' => array( 35 ),
'rows' => array( 0 ),
'tags' => array( 'nikwali_fieldheadercolumn' ),
'items' => array( 'simple_grid_field87' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field36' => array( 'cols' => array( 36 ),
'rows' => array( 0 ),
'tags' => array( 'tanggallahir4_fieldheadercolumn' ),
'items' => array( 'simple_grid_field88' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field37' => array( 'cols' => array( 37 ),
'rows' => array( 0 ),
'tags' => array( 'pendidikan3_fieldheadercolumn' ),
'items' => array( 'simple_grid_field89' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field38' => array( 'cols' => array( 38 ),
'rows' => array( 0 ),
'tags' => array( 'pekerjaan3_fieldheadercolumn' ),
'items' => array( 'simple_grid_field90' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field39' => array( 'cols' => array( 39 ),
'rows' => array( 0 ),
'tags' => array( 'penghasilan3_fieldheadercolumn' ),
'items' => array( 'simple_grid_field91' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field40' => array( 'cols' => array( 40 ),
'rows' => array( 0 ),
'tags' => array( 'kontak_fieldheadercolumn' ),
'items' => array( 'simple_grid_field92' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field41' => array( 'cols' => array( 41 ),
'rows' => array( 0 ),
'tags' => array( 'nomorwa_fieldheadercolumn' ),
'items' => array( 'simple_grid_field93' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field42' => array( 'cols' => array( 42 ),
'rows' => array( 0 ),
'tags' => array( 'email_fieldheadercolumn' ),
'items' => array( 'simple_grid_field94' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field43' => array( 'cols' => array( 43 ),
'rows' => array( 0 ),
'tags' => array( 'tinggibadan_fieldheadercolumn' ),
'items' => array( 'simple_grid_field95' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field44' => array( 'cols' => array( 44 ),
'rows' => array( 0 ),
'tags' => array( 'beratbadan_fieldheadercolumn' ),
'items' => array( 'simple_grid_field96' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field45' => array( 'cols' => array( 45 ),
'rows' => array( 0 ),
'tags' => array( 'jaraktempatkesekolah_fieldheadercolumn' ),
'items' => array( 'simple_grid_field97' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field46' => array( 'cols' => array( 46 ),
'rows' => array( 0 ),
'tags' => array( 'jumlahsaudarakandung_fieldheadercolumn' ),
'items' => array( 'simple_grid_field98' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field47' => array( 'cols' => array( 47 ),
'rows' => array( 0 ),
'tags' => array( 'asaltk_fieldheadercolumn' ),
'items' => array( 'simple_grid_field99' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field48' => array( 'cols' => array( 48 ),
'rows' => array( 0 ),
'tags' => array( 'nomorsurattk_fieldheadercolumn' ),
'items' => array( 'simple_grid_field100' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field49' => array( 'cols' => array( 49 ),
'rows' => array( 0 ),
'tags' => array( 'paktaintegritas_fieldheadercolumn' ),
'items' => array( 'simple_grid_field101' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field50' => array( 'cols' => array( 50 ),
'rows' => array( 0 ),
'tags' => array( 'namaibu_fieldheadercolumn' ),
'items' => array( 'simple_grid_field102' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field51' => array( 'cols' => array( 51 ),
'rows' => array( 0 ),
'tags' => array( 'status_fieldheadercolumn' ),
'items' => array( 'simple_grid_field103' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array( 'ID_fieldcolumn' ),
'items' => array( 'simple_grid_field' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field1' => array( 'cols' => array( 1 ),
'rows' => array( 1 ),
'tags' => array( 'tanggaldaftar_fieldcolumn' ),
'items' => array( 'simple_grid_field1' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field2' => array( 'cols' => array( 2 ),
'rows' => array( 1 ),
'tags' => array( 'nomap_fieldcolumn' ),
'items' => array( 'simple_grid_field2' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field3' => array( 'cols' => array( 3 ),
'rows' => array( 1 ),
'tags' => array( 'namalengkap_fieldcolumn' ),
'items' => array( 'simple_grid_field3' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field4' => array( 'cols' => array( 4 ),
'rows' => array( 1 ),
'tags' => array( 'jeniskelamin_fieldcolumn' ),
'items' => array( 'simple_grid_field4' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field5' => array( 'cols' => array( 5 ),
'rows' => array( 1 ),
'tags' => array( 'nisn_fieldcolumn' ),
'items' => array( 'simple_grid_field5' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field6' => array( 'cols' => array( 6 ),
'rows' => array( 1 ),
'tags' => array( 'nik_fieldcolumn' ),
'items' => array( 'simple_grid_field6' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field7' => array( 'cols' => array( 7 ),
'rows' => array( 1 ),
'tags' => array( 'tempatlahir_fieldcolumn' ),
'items' => array( 'simple_grid_field7' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field8' => array( 'cols' => array( 8 ),
'rows' => array( 1 ),
'tags' => array( 'tanggallahir1_fieldcolumn' ),
'items' => array( 'simple_grid_field8' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field9' => array( 'cols' => array( 9 ),
'rows' => array( 1 ),
'tags' => array( 'noaktalahir_fieldcolumn' ),
'items' => array( 'simple_grid_field9' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field10' => array( 'cols' => array( 10 ),
'rows' => array( 1 ),
'tags' => array( 'agama_fieldcolumn' ),
'items' => array( 'simple_grid_field10' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field11' => array( 'cols' => array( 11 ),
'rows' => array( 1 ),
'tags' => array( 'alamatjalan_fieldcolumn' ),
'items' => array( 'simple_grid_field11' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field12' => array( 'cols' => array( 12 ),
'rows' => array( 1 ),
'tags' => array( 'rt_fieldcolumn' ),
'items' => array( 'simple_grid_field12' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field13' => array( 'cols' => array( 13 ),
'rows' => array( 1 ),
'tags' => array( 'rw_fieldcolumn' ),
'items' => array( 'simple_grid_field13' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field14' => array( 'cols' => array( 14 ),
'rows' => array( 1 ),
'tags' => array( 'dusun_fieldcolumn' ),
'items' => array( 'simple_grid_field14' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field15' => array( 'cols' => array( 15 ),
'rows' => array( 1 ),
'tags' => array( 'deskel_fieldcolumn' ),
'items' => array( 'simple_grid_field15' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field16' => array( 'cols' => array( 16 ),
'rows' => array( 1 ),
'tags' => array( 'kecamatan_fieldcolumn' ),
'items' => array( 'simple_grid_field16' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field17' => array( 'cols' => array( 17 ),
'rows' => array( 1 ),
'tags' => array( 'kodepos_fieldcolumn' ),
'items' => array( 'simple_grid_field17' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field18' => array( 'cols' => array( 18 ),
'rows' => array( 1 ),
'tags' => array( 'tempattinggal_fieldcolumn' ),
'items' => array( 'simple_grid_field18' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field19' => array( 'cols' => array( 19 ),
'rows' => array( 1 ),
'tags' => array( 'modatransportasi_fieldcolumn' ),
'items' => array( 'simple_grid_field19' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field20' => array( 'cols' => array( 20 ),
'rows' => array( 1 ),
'tags' => array( 'anakke_fieldcolumn' ),
'items' => array( 'simple_grid_field20' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field21' => array( 'cols' => array( 21 ),
'rows' => array( 1 ),
'tags' => array( 'namaayah_fieldcolumn' ),
'items' => array( 'simple_grid_field21' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field22' => array( 'cols' => array( 22 ),
'rows' => array( 1 ),
'tags' => array( 'nikayah_fieldcolumn' ),
'items' => array( 'simple_grid_field22' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field23' => array( 'cols' => array( 23 ),
'rows' => array( 1 ),
'tags' => array( 'tanggallahir2_fieldcolumn' ),
'items' => array( 'simple_grid_field23' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field24' => array( 'cols' => array( 24 ),
'rows' => array( 1 ),
'tags' => array( 'pendidikan1_fieldcolumn' ),
'items' => array( 'simple_grid_field24' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field25' => array( 'cols' => array( 25 ),
'rows' => array( 1 ),
'tags' => array( 'pekerjaan1_fieldcolumn' ),
'items' => array( 'simple_grid_field25' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field26' => array( 'cols' => array( 26 ),
'rows' => array( 1 ),
'tags' => array( 'penghasilan1_fieldcolumn' ),
'items' => array( 'simple_grid_field26' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field27' => array( 'cols' => array( 27 ),
'rows' => array( 1 ),
'tags' => array( 'statusayah_fieldcolumn' ),
'items' => array( 'simple_grid_field27' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field28' => array( 'cols' => array( 28 ),
'rows' => array( 1 ),
'tags' => array( 'statusibu_fieldcolumn' ),
'items' => array( 'simple_grid_field28' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field29' => array( 'cols' => array( 29 ),
'rows' => array( 1 ),
'tags' => array( 'nikibu_fieldcolumn' ),
'items' => array( 'simple_grid_field29' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field30' => array( 'cols' => array( 30 ),
'rows' => array( 1 ),
'tags' => array( 'tanggallahir3_fieldcolumn' ),
'items' => array( 'simple_grid_field30' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field31' => array( 'cols' => array( 31 ),
'rows' => array( 1 ),
'tags' => array( 'pendidikan2_fieldcolumn' ),
'items' => array( 'simple_grid_field31' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field32' => array( 'cols' => array( 32 ),
'rows' => array( 1 ),
'tags' => array( 'pekerjaan2_fieldcolumn' ),
'items' => array( 'simple_grid_field32' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field33' => array( 'cols' => array( 33 ),
'rows' => array( 1 ),
'tags' => array( 'penghasilan2_fieldcolumn' ),
'items' => array( 'simple_grid_field33' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field34' => array( 'cols' => array( 34 ),
'rows' => array( 1 ),
'tags' => array( 'namawali_fieldcolumn' ),
'items' => array( 'simple_grid_field34' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field35' => array( 'cols' => array( 35 ),
'rows' => array( 1 ),
'tags' => array( 'nikwali_fieldcolumn' ),
'items' => array( 'simple_grid_field35' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field36' => array( 'cols' => array( 36 ),
'rows' => array( 1 ),
'tags' => array( 'tanggallahir4_fieldcolumn' ),
'items' => array( 'simple_grid_field36' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field37' => array( 'cols' => array( 37 ),
'rows' => array( 1 ),
'tags' => array( 'pendidikan3_fieldcolumn' ),
'items' => array( 'simple_grid_field37' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field38' => array( 'cols' => array( 38 ),
'rows' => array( 1 ),
'tags' => array( 'pekerjaan3_fieldcolumn' ),
'items' => array( 'simple_grid_field38' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field39' => array( 'cols' => array( 39 ),
'rows' => array( 1 ),
'tags' => array( 'penghasilan3_fieldcolumn' ),
'items' => array( 'simple_grid_field39' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field40' => array( 'cols' => array( 40 ),
'rows' => array( 1 ),
'tags' => array( 'kontak_fieldcolumn' ),
'items' => array( 'simple_grid_field40' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field41' => array( 'cols' => array( 41 ),
'rows' => array( 1 ),
'tags' => array( 'nomorwa_fieldcolumn' ),
'items' => array( 'simple_grid_field41' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field42' => array( 'cols' => array( 42 ),
'rows' => array( 1 ),
'tags' => array( 'email_fieldcolumn' ),
'items' => array( 'simple_grid_field42' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field43' => array( 'cols' => array( 43 ),
'rows' => array( 1 ),
'tags' => array( 'tinggibadan_fieldcolumn' ),
'items' => array( 'simple_grid_field43' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field44' => array( 'cols' => array( 44 ),
'rows' => array( 1 ),
'tags' => array( 'beratbadan_fieldcolumn' ),
'items' => array( 'simple_grid_field44' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field45' => array( 'cols' => array( 45 ),
'rows' => array( 1 ),
'tags' => array( 'jaraktempatkesekolah_fieldcolumn' ),
'items' => array( 'simple_grid_field45' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field46' => array( 'cols' => array( 46 ),
'rows' => array( 1 ),
'tags' => array( 'jumlahsaudarakandung_fieldcolumn' ),
'items' => array( 'simple_grid_field46' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field47' => array( 'cols' => array( 47 ),
'rows' => array( 1 ),
'tags' => array( 'asaltk_fieldcolumn' ),
'items' => array( 'simple_grid_field47' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field48' => array( 'cols' => array( 48 ),
'rows' => array( 1 ),
'tags' => array( 'nomorsurattk_fieldcolumn' ),
'items' => array( 'simple_grid_field48' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field49' => array( 'cols' => array( 49 ),
'rows' => array( 1 ),
'tags' => array( 'paktaintegritas_fieldcolumn' ),
'items' => array( 'simple_grid_field49' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field50' => array( 'cols' => array( 50 ),
'rows' => array( 1 ),
'tags' => array( 'namaibu_fieldcolumn' ),
'items' => array( 'simple_grid_field50' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field51' => array( 'cols' => array( 51 ),
'rows' => array( 1 ),
'tags' => array( 'status_fieldcolumn' ),
'items' => array( 'simple_grid_field51' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field' => array( 'cols' => array( 0 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field1' => array( 'cols' => array( 1 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field2' => array( 'cols' => array( 2 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field3' => array( 'cols' => array( 3 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field4' => array( 'cols' => array( 4 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field5' => array( 'cols' => array( 5 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field6' => array( 'cols' => array( 6 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field7' => array( 'cols' => array( 7 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field8' => array( 'cols' => array( 8 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field9' => array( 'cols' => array( 9 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field10' => array( 'cols' => array( 10 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field11' => array( 'cols' => array( 11 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field12' => array( 'cols' => array( 12 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field13' => array( 'cols' => array( 13 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field14' => array( 'cols' => array( 14 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field15' => array( 'cols' => array( 15 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field16' => array( 'cols' => array( 16 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field17' => array( 'cols' => array( 17 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field18' => array( 'cols' => array( 18 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field19' => array( 'cols' => array( 19 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field20' => array( 'cols' => array( 20 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field21' => array( 'cols' => array( 21 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field22' => array( 'cols' => array( 22 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field23' => array( 'cols' => array( 23 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field24' => array( 'cols' => array( 24 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field25' => array( 'cols' => array( 25 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field26' => array( 'cols' => array( 26 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field27' => array( 'cols' => array( 27 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field28' => array( 'cols' => array( 28 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field29' => array( 'cols' => array( 29 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field30' => array( 'cols' => array( 30 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field31' => array( 'cols' => array( 31 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field32' => array( 'cols' => array( 32 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field33' => array( 'cols' => array( 33 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field34' => array( 'cols' => array( 34 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field35' => array( 'cols' => array( 35 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field36' => array( 'cols' => array( 36 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field37' => array( 'cols' => array( 37 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field38' => array( 'cols' => array( 38 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field39' => array( 'cols' => array( 39 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field40' => array( 'cols' => array( 40 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field41' => array( 'cols' => array( 41 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field42' => array( 'cols' => array( 42 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field43' => array( 'cols' => array( 43 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field44' => array( 'cols' => array( 44 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field45' => array( 'cols' => array( 45 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field46' => array( 'cols' => array( 46 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field47' => array( 'cols' => array( 47 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field48' => array( 'cols' => array( 48 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field49' => array( 'cols' => array( 49 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field50' => array( 'cols' => array( 50 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field51' => array( 'cols' => array( 51 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ) ),
'width' => 52,
'height' => 3 ) ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array( 'print_pages' => array( 'tag' => 'PRINT_PAGES',
'type' => 2 ) ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'gridType' => 0,
'recsPerRow' => 1,
'hasCustomButtons' => false ),
'misc' => array( 'type' => 'print',
'breadcrumb' => false ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'dataGrid' => array( 'groupFields' => array(  ) ) );
			$pageArray = array( 'id' => 'print',
'type' => 'print',
'layoutId' => 'basic',
'disabled' => 0,
'default' => 0,
'forms' => array( 'top' => array( 'modelId' => 'print-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c2' => array( 'model' => 'c2',
'items' => array( 'print_header',
'print_subheader' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'above-grid' => array( 'modelId' => 'print-above-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'print_pages' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'below-grid' => array( 'modelId' => 'print-below-grid',
'grid' => array(  ),
'cells' => array(  ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'horizontal-grid',
'grid' => array( array( 'section' => 'head',
'cells' => array( array( 'cell' => 'headcell_field' ),
array( 'cell' => 'headcell_field1' ),
array( 'cell' => 'headcell_field2' ),
array( 'cell' => 'headcell_field3' ),
array( 'cell' => 'headcell_field4' ),
array( 'cell' => 'headcell_field5' ),
array( 'cell' => 'headcell_field6' ),
array( 'cell' => 'headcell_field7' ),
array( 'cell' => 'headcell_field8' ),
array( 'cell' => 'headcell_field9' ),
array( 'cell' => 'headcell_field10' ),
array( 'cell' => 'headcell_field11' ),
array( 'cell' => 'headcell_field12' ),
array( 'cell' => 'headcell_field13' ),
array( 'cell' => 'headcell_field14' ),
array( 'cell' => 'headcell_field15' ),
array( 'cell' => 'headcell_field16' ),
array( 'cell' => 'headcell_field17' ),
array( 'cell' => 'headcell_field18' ),
array( 'cell' => 'headcell_field19' ),
array( 'cell' => 'headcell_field20' ),
array( 'cell' => 'headcell_field21' ),
array( 'cell' => 'headcell_field22' ),
array( 'cell' => 'headcell_field23' ),
array( 'cell' => 'headcell_field24' ),
array( 'cell' => 'headcell_field25' ),
array( 'cell' => 'headcell_field26' ),
array( 'cell' => 'headcell_field27' ),
array( 'cell' => 'headcell_field28' ),
array( 'cell' => 'headcell_field29' ),
array( 'cell' => 'headcell_field30' ),
array( 'cell' => 'headcell_field31' ),
array( 'cell' => 'headcell_field32' ),
array( 'cell' => 'headcell_field33' ),
array( 'cell' => 'headcell_field34' ),
array( 'cell' => 'headcell_field35' ),
array( 'cell' => 'headcell_field36' ),
array( 'cell' => 'headcell_field37' ),
array( 'cell' => 'headcell_field38' ),
array( 'cell' => 'headcell_field39' ),
array( 'cell' => 'headcell_field40' ),
array( 'cell' => 'headcell_field41' ),
array( 'cell' => 'headcell_field42' ),
array( 'cell' => 'headcell_field43' ),
array( 'cell' => 'headcell_field44' ),
array( 'cell' => 'headcell_field45' ),
array( 'cell' => 'headcell_field46' ),
array( 'cell' => 'headcell_field47' ),
array( 'cell' => 'headcell_field48' ),
array( 'cell' => 'headcell_field49' ),
array( 'cell' => 'headcell_field50' ),
array( 'cell' => 'headcell_field51' ) ) ),
array( 'section' => 'body',
'cells' => array( array( 'cell' => 'cell_field' ),
array( 'cell' => 'cell_field1' ),
array( 'cell' => 'cell_field2' ),
array( 'cell' => 'cell_field3' ),
array( 'cell' => 'cell_field4' ),
array( 'cell' => 'cell_field5' ),
array( 'cell' => 'cell_field6' ),
array( 'cell' => 'cell_field7' ),
array( 'cell' => 'cell_field8' ),
array( 'cell' => 'cell_field9' ),
array( 'cell' => 'cell_field10' ),
array( 'cell' => 'cell_field11' ),
array( 'cell' => 'cell_field12' ),
array( 'cell' => 'cell_field13' ),
array( 'cell' => 'cell_field14' ),
array( 'cell' => 'cell_field15' ),
array( 'cell' => 'cell_field16' ),
array( 'cell' => 'cell_field17' ),
array( 'cell' => 'cell_field18' ),
array( 'cell' => 'cell_field19' ),
array( 'cell' => 'cell_field20' ),
array( 'cell' => 'cell_field21' ),
array( 'cell' => 'cell_field22' ),
array( 'cell' => 'cell_field23' ),
array( 'cell' => 'cell_field24' ),
array( 'cell' => 'cell_field25' ),
array( 'cell' => 'cell_field26' ),
array( 'cell' => 'cell_field27' ),
array( 'cell' => 'cell_field28' ),
array( 'cell' => 'cell_field29' ),
array( 'cell' => 'cell_field30' ),
array( 'cell' => 'cell_field31' ),
array( 'cell' => 'cell_field32' ),
array( 'cell' => 'cell_field33' ),
array( 'cell' => 'cell_field34' ),
array( 'cell' => 'cell_field35' ),
array( 'cell' => 'cell_field36' ),
array( 'cell' => 'cell_field37' ),
array( 'cell' => 'cell_field38' ),
array( 'cell' => 'cell_field39' ),
array( 'cell' => 'cell_field40' ),
array( 'cell' => 'cell_field41' ),
array( 'cell' => 'cell_field42' ),
array( 'cell' => 'cell_field43' ),
array( 'cell' => 'cell_field44' ),
array( 'cell' => 'cell_field45' ),
array( 'cell' => 'cell_field46' ),
array( 'cell' => 'cell_field47' ),
array( 'cell' => 'cell_field48' ),
array( 'cell' => 'cell_field49' ),
array( 'cell' => 'cell_field50' ),
array( 'cell' => 'cell_field51' ) ) ),
array( 'section' => 'foot',
'cells' => array( array( 'cell' => 'footcell_field' ),
array( 'cell' => 'footcell_field1' ),
array( 'cell' => 'footcell_field2' ),
array( 'cell' => 'footcell_field3' ),
array( 'cell' => 'footcell_field4' ),
array( 'cell' => 'footcell_field5' ),
array( 'cell' => 'footcell_field6' ),
array( 'cell' => 'footcell_field7' ),
array( 'cell' => 'footcell_field8' ),
array( 'cell' => 'footcell_field9' ),
array( 'cell' => 'footcell_field10' ),
array( 'cell' => 'footcell_field11' ),
array( 'cell' => 'footcell_field12' ),
array( 'cell' => 'footcell_field13' ),
array( 'cell' => 'footcell_field14' ),
array( 'cell' => 'footcell_field15' ),
array( 'cell' => 'footcell_field16' ),
array( 'cell' => 'footcell_field17' ),
array( 'cell' => 'footcell_field18' ),
array( 'cell' => 'footcell_field19' ),
array( 'cell' => 'footcell_field20' ),
array( 'cell' => 'footcell_field21' ),
array( 'cell' => 'footcell_field22' ),
array( 'cell' => 'footcell_field23' ),
array( 'cell' => 'footcell_field24' ),
array( 'cell' => 'footcell_field25' ),
array( 'cell' => 'footcell_field26' ),
array( 'cell' => 'footcell_field27' ),
array( 'cell' => 'footcell_field28' ),
array( 'cell' => 'footcell_field29' ),
array( 'cell' => 'footcell_field30' ),
array( 'cell' => 'footcell_field31' ),
array( 'cell' => 'footcell_field32' ),
array( 'cell' => 'footcell_field33' ),
array( 'cell' => 'footcell_field34' ),
array( 'cell' => 'footcell_field35' ),
array( 'cell' => 'footcell_field36' ),
array( 'cell' => 'footcell_field37' ),
array( 'cell' => 'footcell_field38' ),
array( 'cell' => 'footcell_field39' ),
array( 'cell' => 'footcell_field40' ),
array( 'cell' => 'footcell_field41' ),
array( 'cell' => 'footcell_field42' ),
array( 'cell' => 'footcell_field43' ),
array( 'cell' => 'footcell_field44' ),
array( 'cell' => 'footcell_field45' ),
array( 'cell' => 'footcell_field46' ),
array( 'cell' => 'footcell_field47' ),
array( 'cell' => 'footcell_field48' ),
array( 'cell' => 'footcell_field49' ),
array( 'cell' => 'footcell_field50' ),
array( 'cell' => 'footcell_field51' ) ) ) ),
'cells' => array( 'headcell_field' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field52' ),
'field' => 'ID',
'columnName' => 'field' ),
'cell_field' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field' ),
'field' => 'ID',
'columnName' => 'field' ),
'footcell_field' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field1' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field53' ),
'field' => 'tanggaldaftar',
'columnName' => 'field' ),
'cell_field1' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field1' ),
'field' => 'tanggaldaftar',
'columnName' => 'field' ),
'footcell_field1' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field2' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field54' ),
'field' => 'nomap',
'columnName' => 'field' ),
'cell_field2' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field2' ),
'field' => 'nomap',
'columnName' => 'field' ),
'footcell_field2' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field3' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field55' ),
'field' => 'namalengkap',
'columnName' => 'field' ),
'cell_field3' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field3' ),
'field' => 'namalengkap',
'columnName' => 'field' ),
'footcell_field3' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field4' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field56' ),
'field' => 'jeniskelamin',
'columnName' => 'field' ),
'cell_field4' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field4' ),
'field' => 'jeniskelamin',
'columnName' => 'field' ),
'footcell_field4' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field5' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field57' ),
'field' => 'nisn',
'columnName' => 'field' ),
'cell_field5' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field5' ),
'field' => 'nisn',
'columnName' => 'field' ),
'footcell_field5' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field6' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field58' ),
'field' => 'nik',
'columnName' => 'field' ),
'cell_field6' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field6' ),
'field' => 'nik',
'columnName' => 'field' ),
'footcell_field6' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field7' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field59' ),
'field' => 'tempatlahir',
'columnName' => 'field' ),
'cell_field7' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field7' ),
'field' => 'tempatlahir',
'columnName' => 'field' ),
'footcell_field7' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field8' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field60' ),
'field' => 'tanggallahir1',
'columnName' => 'field' ),
'cell_field8' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field8' ),
'field' => 'tanggallahir1',
'columnName' => 'field' ),
'footcell_field8' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field9' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field61' ),
'field' => 'noaktalahir',
'columnName' => 'field' ),
'cell_field9' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field9' ),
'field' => 'noaktalahir',
'columnName' => 'field' ),
'footcell_field9' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field10' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field62' ),
'field' => 'agama',
'columnName' => 'field' ),
'cell_field10' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field10' ),
'field' => 'agama',
'columnName' => 'field' ),
'footcell_field10' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field11' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field63' ),
'field' => 'alamatjalan',
'columnName' => 'field' ),
'cell_field11' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field11' ),
'field' => 'alamatjalan',
'columnName' => 'field' ),
'footcell_field11' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field12' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field64' ),
'field' => 'rt',
'columnName' => 'field' ),
'cell_field12' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field12' ),
'field' => 'rt',
'columnName' => 'field' ),
'footcell_field12' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field13' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field65' ),
'field' => 'rw',
'columnName' => 'field' ),
'cell_field13' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field13' ),
'field' => 'rw',
'columnName' => 'field' ),
'footcell_field13' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field14' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field66' ),
'field' => 'dusun',
'columnName' => 'field' ),
'cell_field14' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field14' ),
'field' => 'dusun',
'columnName' => 'field' ),
'footcell_field14' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field15' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field67' ),
'field' => 'deskel',
'columnName' => 'field' ),
'cell_field15' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field15' ),
'field' => 'deskel',
'columnName' => 'field' ),
'footcell_field15' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field16' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field68' ),
'field' => 'kecamatan',
'columnName' => 'field' ),
'cell_field16' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field16' ),
'field' => 'kecamatan',
'columnName' => 'field' ),
'footcell_field16' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field17' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field69' ),
'field' => 'kodepos',
'columnName' => 'field' ),
'cell_field17' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field17' ),
'field' => 'kodepos',
'columnName' => 'field' ),
'footcell_field17' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field18' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field70' ),
'field' => 'tempattinggal',
'columnName' => 'field' ),
'cell_field18' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field18' ),
'field' => 'tempattinggal',
'columnName' => 'field' ),
'footcell_field18' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field19' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field71' ),
'field' => 'modatransportasi',
'columnName' => 'field' ),
'cell_field19' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field19' ),
'field' => 'modatransportasi',
'columnName' => 'field' ),
'footcell_field19' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field20' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field72' ),
'field' => 'anakke',
'columnName' => 'field' ),
'cell_field20' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field20' ),
'field' => 'anakke',
'columnName' => 'field' ),
'footcell_field20' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field21' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field73' ),
'field' => 'namaayah',
'columnName' => 'field' ),
'cell_field21' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field21' ),
'field' => 'namaayah',
'columnName' => 'field' ),
'footcell_field21' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field22' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field74' ),
'field' => 'nikayah',
'columnName' => 'field' ),
'cell_field22' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field22' ),
'field' => 'nikayah',
'columnName' => 'field' ),
'footcell_field22' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field23' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field75' ),
'field' => 'tanggallahir2',
'columnName' => 'field' ),
'cell_field23' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field23' ),
'field' => 'tanggallahir2',
'columnName' => 'field' ),
'footcell_field23' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field24' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field76' ),
'field' => 'pendidikan1',
'columnName' => 'field' ),
'cell_field24' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field24' ),
'field' => 'pendidikan1',
'columnName' => 'field' ),
'footcell_field24' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field25' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field77' ),
'field' => 'pekerjaan1',
'columnName' => 'field' ),
'cell_field25' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field25' ),
'field' => 'pekerjaan1',
'columnName' => 'field' ),
'footcell_field25' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field26' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field78' ),
'field' => 'penghasilan1',
'columnName' => 'field' ),
'cell_field26' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field26' ),
'field' => 'penghasilan1',
'columnName' => 'field' ),
'footcell_field26' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field27' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field79' ),
'field' => 'statusayah',
'columnName' => 'field' ),
'cell_field27' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field27' ),
'field' => 'statusayah',
'columnName' => 'field' ),
'footcell_field27' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field28' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field80' ),
'field' => 'statusibu',
'columnName' => 'field' ),
'cell_field28' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field28' ),
'field' => 'statusibu',
'columnName' => 'field' ),
'footcell_field28' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field29' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field81' ),
'field' => 'nikibu',
'columnName' => 'field' ),
'cell_field29' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field29' ),
'field' => 'nikibu',
'columnName' => 'field' ),
'footcell_field29' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field30' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field82' ),
'field' => 'tanggallahir3',
'columnName' => 'field' ),
'cell_field30' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field30' ),
'field' => 'tanggallahir3',
'columnName' => 'field' ),
'footcell_field30' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field31' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field83' ),
'field' => 'pendidikan2',
'columnName' => 'field' ),
'cell_field31' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field31' ),
'field' => 'pendidikan2',
'columnName' => 'field' ),
'footcell_field31' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field32' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field84' ),
'field' => 'pekerjaan2',
'columnName' => 'field' ),
'cell_field32' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field32' ),
'field' => 'pekerjaan2',
'columnName' => 'field' ),
'footcell_field32' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field33' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field85' ),
'field' => 'penghasilan2',
'columnName' => 'field' ),
'cell_field33' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field33' ),
'field' => 'penghasilan2',
'columnName' => 'field' ),
'footcell_field33' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field34' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field86' ),
'field' => 'namawali',
'columnName' => 'field' ),
'cell_field34' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field34' ),
'field' => 'namawali',
'columnName' => 'field' ),
'footcell_field34' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field35' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field87' ),
'field' => 'nikwali',
'columnName' => 'field' ),
'cell_field35' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field35' ),
'field' => 'nikwali',
'columnName' => 'field' ),
'footcell_field35' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field36' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field88' ),
'field' => 'tanggallahir4',
'columnName' => 'field' ),
'cell_field36' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field36' ),
'field' => 'tanggallahir4',
'columnName' => 'field' ),
'footcell_field36' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field37' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field89' ),
'field' => 'pendidikan3',
'columnName' => 'field' ),
'cell_field37' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field37' ),
'field' => 'pendidikan3',
'columnName' => 'field' ),
'footcell_field37' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field38' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field90' ),
'field' => 'pekerjaan3',
'columnName' => 'field' ),
'cell_field38' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field38' ),
'field' => 'pekerjaan3',
'columnName' => 'field' ),
'footcell_field38' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field39' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field91' ),
'field' => 'penghasilan3',
'columnName' => 'field' ),
'cell_field39' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field39' ),
'field' => 'penghasilan3',
'columnName' => 'field' ),
'footcell_field39' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field40' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field92' ),
'field' => 'kontak',
'columnName' => 'field' ),
'cell_field40' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field40' ),
'field' => 'kontak',
'columnName' => 'field' ),
'footcell_field40' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field41' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field93' ),
'field' => 'nomorwa',
'columnName' => 'field' ),
'cell_field41' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field41' ),
'field' => 'nomorwa',
'columnName' => 'field' ),
'footcell_field41' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field42' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field94' ),
'field' => 'email',
'columnName' => 'field' ),
'cell_field42' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field42' ),
'field' => 'email',
'columnName' => 'field' ),
'footcell_field42' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field43' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field95' ),
'field' => 'tinggibadan',
'columnName' => 'field' ),
'cell_field43' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field43' ),
'field' => 'tinggibadan',
'columnName' => 'field' ),
'footcell_field43' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field44' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field96' ),
'field' => 'beratbadan',
'columnName' => 'field' ),
'cell_field44' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field44' ),
'field' => 'beratbadan',
'columnName' => 'field' ),
'footcell_field44' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field45' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field97' ),
'field' => 'jaraktempatkesekolah',
'columnName' => 'field' ),
'cell_field45' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field45' ),
'field' => 'jaraktempatkesekolah',
'columnName' => 'field' ),
'footcell_field45' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field46' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field98' ),
'field' => 'jumlahsaudarakandung',
'columnName' => 'field' ),
'cell_field46' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field46' ),
'field' => 'jumlahsaudarakandung',
'columnName' => 'field' ),
'footcell_field46' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field47' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field99' ),
'field' => 'asaltk',
'columnName' => 'field' ),
'cell_field47' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field47' ),
'field' => 'asaltk',
'columnName' => 'field' ),
'footcell_field47' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field48' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field100' ),
'field' => 'nomorsurattk',
'columnName' => 'field' ),
'cell_field48' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field48' ),
'field' => 'nomorsurattk',
'columnName' => 'field' ),
'footcell_field48' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field49' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field101' ),
'field' => 'paktaintegritas',
'columnName' => 'field' ),
'cell_field49' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field49' ),
'field' => 'paktaintegritas',
'columnName' => 'field' ),
'footcell_field49' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field50' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field102' ),
'field' => 'namaibu',
'columnName' => 'field' ),
'cell_field50' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field50' ),
'field' => 'namaibu',
'columnName' => 'field' ),
'footcell_field50' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field51' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field103' ),
'field' => 'status',
'columnName' => 'field' ),
'cell_field51' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field51' ),
'field' => 'status',
'columnName' => 'field' ),
'footcell_field51' => array( 'model' => 'footcell_field',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'print_header' => array( 'type' => 'print_header' ),
'print_subheader' => array( 'type' => 'print_subheader' ),
'print_pages' => array( 'type' => 'print_pages' ),
'simple_grid_field' => array( 'field' => 'ID',
'type' => 'grid_field' ),
'simple_grid_field52' => array( 'type' => 'grid_field_label',
'field' => 'ID' ),
'simple_grid_field1' => array( 'field' => 'tanggaldaftar',
'type' => 'grid_field' ),
'simple_grid_field53' => array( 'type' => 'grid_field_label',
'field' => 'tanggaldaftar' ),
'simple_grid_field2' => array( 'field' => 'nomap',
'type' => 'grid_field' ),
'simple_grid_field54' => array( 'type' => 'grid_field_label',
'field' => 'nomap' ),
'simple_grid_field3' => array( 'field' => 'namalengkap',
'type' => 'grid_field' ),
'simple_grid_field55' => array( 'type' => 'grid_field_label',
'field' => 'namalengkap' ),
'simple_grid_field4' => array( 'field' => 'jeniskelamin',
'type' => 'grid_field' ),
'simple_grid_field56' => array( 'type' => 'grid_field_label',
'field' => 'jeniskelamin' ),
'simple_grid_field5' => array( 'field' => 'nisn',
'type' => 'grid_field' ),
'simple_grid_field57' => array( 'type' => 'grid_field_label',
'field' => 'nisn' ),
'simple_grid_field6' => array( 'field' => 'nik',
'type' => 'grid_field' ),
'simple_grid_field58' => array( 'type' => 'grid_field_label',
'field' => 'nik' ),
'simple_grid_field7' => array( 'field' => 'tempatlahir',
'type' => 'grid_field' ),
'simple_grid_field59' => array( 'type' => 'grid_field_label',
'field' => 'tempatlahir' ),
'simple_grid_field8' => array( 'field' => 'tanggallahir1',
'type' => 'grid_field' ),
'simple_grid_field60' => array( 'type' => 'grid_field_label',
'field' => 'tanggallahir1' ),
'simple_grid_field9' => array( 'field' => 'noaktalahir',
'type' => 'grid_field' ),
'simple_grid_field61' => array( 'type' => 'grid_field_label',
'field' => 'noaktalahir' ),
'simple_grid_field10' => array( 'field' => 'agama',
'type' => 'grid_field' ),
'simple_grid_field62' => array( 'type' => 'grid_field_label',
'field' => 'agama' ),
'simple_grid_field11' => array( 'field' => 'alamatjalan',
'type' => 'grid_field' ),
'simple_grid_field63' => array( 'type' => 'grid_field_label',
'field' => 'alamatjalan' ),
'simple_grid_field12' => array( 'field' => 'rt',
'type' => 'grid_field' ),
'simple_grid_field64' => array( 'type' => 'grid_field_label',
'field' => 'rt' ),
'simple_grid_field13' => array( 'field' => 'rw',
'type' => 'grid_field' ),
'simple_grid_field65' => array( 'type' => 'grid_field_label',
'field' => 'rw' ),
'simple_grid_field14' => array( 'field' => 'dusun',
'type' => 'grid_field' ),
'simple_grid_field66' => array( 'type' => 'grid_field_label',
'field' => 'dusun' ),
'simple_grid_field15' => array( 'field' => 'deskel',
'type' => 'grid_field' ),
'simple_grid_field67' => array( 'type' => 'grid_field_label',
'field' => 'deskel' ),
'simple_grid_field16' => array( 'field' => 'kecamatan',
'type' => 'grid_field' ),
'simple_grid_field68' => array( 'type' => 'grid_field_label',
'field' => 'kecamatan' ),
'simple_grid_field17' => array( 'field' => 'kodepos',
'type' => 'grid_field' ),
'simple_grid_field69' => array( 'type' => 'grid_field_label',
'field' => 'kodepos' ),
'simple_grid_field18' => array( 'field' => 'tempattinggal',
'type' => 'grid_field' ),
'simple_grid_field70' => array( 'type' => 'grid_field_label',
'field' => 'tempattinggal' ),
'simple_grid_field19' => array( 'field' => 'modatransportasi',
'type' => 'grid_field' ),
'simple_grid_field71' => array( 'type' => 'grid_field_label',
'field' => 'modatransportasi' ),
'simple_grid_field20' => array( 'field' => 'anakke',
'type' => 'grid_field' ),
'simple_grid_field72' => array( 'type' => 'grid_field_label',
'field' => 'anakke' ),
'simple_grid_field21' => array( 'field' => 'namaayah',
'type' => 'grid_field' ),
'simple_grid_field73' => array( 'type' => 'grid_field_label',
'field' => 'namaayah' ),
'simple_grid_field22' => array( 'field' => 'nikayah',
'type' => 'grid_field' ),
'simple_grid_field74' => array( 'type' => 'grid_field_label',
'field' => 'nikayah' ),
'simple_grid_field23' => array( 'field' => 'tanggallahir2',
'type' => 'grid_field' ),
'simple_grid_field75' => array( 'type' => 'grid_field_label',
'field' => 'tanggallahir2' ),
'simple_grid_field24' => array( 'field' => 'pendidikan1',
'type' => 'grid_field' ),
'simple_grid_field76' => array( 'type' => 'grid_field_label',
'field' => 'pendidikan1' ),
'simple_grid_field25' => array( 'field' => 'pekerjaan1',
'type' => 'grid_field' ),
'simple_grid_field77' => array( 'type' => 'grid_field_label',
'field' => 'pekerjaan1' ),
'simple_grid_field26' => array( 'field' => 'penghasilan1',
'type' => 'grid_field' ),
'simple_grid_field78' => array( 'type' => 'grid_field_label',
'field' => 'penghasilan1' ),
'simple_grid_field27' => array( 'field' => 'statusayah',
'type' => 'grid_field' ),
'simple_grid_field79' => array( 'type' => 'grid_field_label',
'field' => 'statusayah' ),
'simple_grid_field28' => array( 'field' => 'statusibu',
'type' => 'grid_field' ),
'simple_grid_field80' => array( 'type' => 'grid_field_label',
'field' => 'statusibu' ),
'simple_grid_field29' => array( 'field' => 'nikibu',
'type' => 'grid_field' ),
'simple_grid_field81' => array( 'type' => 'grid_field_label',
'field' => 'nikibu' ),
'simple_grid_field30' => array( 'field' => 'tanggallahir3',
'type' => 'grid_field' ),
'simple_grid_field82' => array( 'type' => 'grid_field_label',
'field' => 'tanggallahir3' ),
'simple_grid_field31' => array( 'field' => 'pendidikan2',
'type' => 'grid_field' ),
'simple_grid_field83' => array( 'type' => 'grid_field_label',
'field' => 'pendidikan2' ),
'simple_grid_field32' => array( 'field' => 'pekerjaan2',
'type' => 'grid_field' ),
'simple_grid_field84' => array( 'type' => 'grid_field_label',
'field' => 'pekerjaan2' ),
'simple_grid_field33' => array( 'field' => 'penghasilan2',
'type' => 'grid_field' ),
'simple_grid_field85' => array( 'type' => 'grid_field_label',
'field' => 'penghasilan2' ),
'simple_grid_field34' => array( 'field' => 'namawali',
'type' => 'grid_field' ),
'simple_grid_field86' => array( 'type' => 'grid_field_label',
'field' => 'namawali' ),
'simple_grid_field35' => array( 'field' => 'nikwali',
'type' => 'grid_field' ),
'simple_grid_field87' => array( 'type' => 'grid_field_label',
'field' => 'nikwali' ),
'simple_grid_field36' => array( 'field' => 'tanggallahir4',
'type' => 'grid_field' ),
'simple_grid_field88' => array( 'type' => 'grid_field_label',
'field' => 'tanggallahir4' ),
'simple_grid_field37' => array( 'field' => 'pendidikan3',
'type' => 'grid_field' ),
'simple_grid_field89' => array( 'type' => 'grid_field_label',
'field' => 'pendidikan3' ),
'simple_grid_field38' => array( 'field' => 'pekerjaan3',
'type' => 'grid_field' ),
'simple_grid_field90' => array( 'type' => 'grid_field_label',
'field' => 'pekerjaan3' ),
'simple_grid_field39' => array( 'field' => 'penghasilan3',
'type' => 'grid_field' ),
'simple_grid_field91' => array( 'type' => 'grid_field_label',
'field' => 'penghasilan3' ),
'simple_grid_field40' => array( 'field' => 'kontak',
'type' => 'grid_field' ),
'simple_grid_field92' => array( 'type' => 'grid_field_label',
'field' => 'kontak' ),
'simple_grid_field41' => array( 'field' => 'nomorwa',
'type' => 'grid_field' ),
'simple_grid_field93' => array( 'type' => 'grid_field_label',
'field' => 'nomorwa' ),
'simple_grid_field42' => array( 'field' => 'email',
'type' => 'grid_field' ),
'simple_grid_field94' => array( 'type' => 'grid_field_label',
'field' => 'email' ),
'simple_grid_field43' => array( 'field' => 'tinggibadan',
'type' => 'grid_field' ),
'simple_grid_field95' => array( 'type' => 'grid_field_label',
'field' => 'tinggibadan' ),
'simple_grid_field44' => array( 'field' => 'beratbadan',
'type' => 'grid_field' ),
'simple_grid_field96' => array( 'type' => 'grid_field_label',
'field' => 'beratbadan' ),
'simple_grid_field45' => array( 'field' => 'jaraktempatkesekolah',
'type' => 'grid_field' ),
'simple_grid_field97' => array( 'type' => 'grid_field_label',
'field' => 'jaraktempatkesekolah' ),
'simple_grid_field46' => array( 'field' => 'jumlahsaudarakandung',
'type' => 'grid_field' ),
'simple_grid_field98' => array( 'type' => 'grid_field_label',
'field' => 'jumlahsaudarakandung' ),
'simple_grid_field47' => array( 'field' => 'asaltk',
'type' => 'grid_field' ),
'simple_grid_field99' => array( 'type' => 'grid_field_label',
'field' => 'asaltk' ),
'simple_grid_field48' => array( 'field' => 'nomorsurattk',
'type' => 'grid_field' ),
'simple_grid_field100' => array( 'type' => 'grid_field_label',
'field' => 'nomorsurattk' ),
'simple_grid_field49' => array( 'field' => 'paktaintegritas',
'type' => 'grid_field' ),
'simple_grid_field101' => array( 'type' => 'grid_field_label',
'field' => 'paktaintegritas' ),
'simple_grid_field50' => array( 'field' => 'namaibu',
'type' => 'grid_field' ),
'simple_grid_field102' => array( 'type' => 'grid_field_label',
'field' => 'namaibu' ),
'simple_grid_field51' => array( 'field' => 'status',
'type' => 'grid_field' ),
'simple_grid_field103' => array( 'type' => 'grid_field_label',
'field' => 'status' ) ),
'dbProps' => array(  ),
'version' => 4 );
		?>