<?php
			$optionsArray = array( 'totals' => array( 'ID' => array( 'totalsType' => '' ),
'tanggaldaftar' => array( 'totalsType' => '' ),
'nomap' => array( 'totalsType' => '' ),
'namalengkap' => array( 'totalsType' => '' ),
'jeniskelamin' => array( 'totalsType' => '' ),
'nisn' => array( 'totalsType' => '' ),
'nik' => array( 'totalsType' => '' ),
'tempatlahir' => array( 'totalsType' => '' ),
'tanggallahir1' => array( 'totalsType' => '' ),
'noaktalahir' => array( 'totalsType' => '' ),
'agama' => array( 'totalsType' => '' ),
'alamatjalan' => array( 'totalsType' => '' ),
'rt' => array( 'totalsType' => '' ),
'rw' => array( 'totalsType' => '' ),
'dusun' => array( 'totalsType' => '' ),
'deskel' => array( 'totalsType' => '' ),
'kecamatan' => array( 'totalsType' => '' ),
'kodepos' => array( 'totalsType' => '' ),
'tempattinggal' => array( 'totalsType' => '' ),
'modatransportasi' => array( 'totalsType' => '' ),
'anakke' => array( 'totalsType' => '' ),
'namaayah' => array( 'totalsType' => '' ),
'nikayah' => array( 'totalsType' => '' ),
'tanggallahir2' => array( 'totalsType' => '' ),
'pendidikan1' => array( 'totalsType' => '' ),
'pekerjaan1' => array( 'totalsType' => '' ),
'penghasilan1' => array( 'totalsType' => '' ),
'statusayah' => array( 'totalsType' => '' ),
'statusibu' => array( 'totalsType' => '' ),
'nikibu' => array( 'totalsType' => '' ),
'tanggallahir3' => array( 'totalsType' => '' ),
'pendidikan2' => array( 'totalsType' => '' ),
'pekerjaan2' => array( 'totalsType' => '' ),
'penghasilan2' => array( 'totalsType' => '' ),
'namawali' => array( 'totalsType' => '' ),
'nikwali' => array( 'totalsType' => '' ),
'tanggallahir4' => array( 'totalsType' => '' ),
'pendidikan3' => array( 'totalsType' => '' ),
'pekerjaan3' => array( 'totalsType' => '' ),
'penghasilan3' => array( 'totalsType' => '' ),
'kontak' => array( 'totalsType' => '' ),
'nomorwa' => array( 'totalsType' => '' ),
'email' => array( 'totalsType' => '' ),
'tinggibadan' => array( 'totalsType' => '' ),
'beratbadan' => array( 'totalsType' => '' ),
'jaraktempatkesekolah' => array( 'totalsType' => '' ),
'jumlahsaudarakandung' => array( 'totalsType' => '' ),
'asaltk' => array( 'totalsType' => '' ),
'nomorsurattk' => array( 'totalsType' => '' ),
'paktaintegritas' => array( 'totalsType' => '' ),
'namaibu' => array( 'totalsType' => '' ),
'status' => array( 'totalsType' => '' ) ),
'fields' => array( 'gridFields' => array( 'ID',
'tanggaldaftar',
'nomap',
'namalengkap',
'jeniskelamin',
'nisn',
'nik',
'tempatlahir',
'tanggallahir1',
'noaktalahir',
'agama',
'alamatjalan',
'rt',
'rw',
'dusun',
'deskel',
'kecamatan',
'kodepos',
'tempattinggal',
'modatransportasi',
'anakke',
'namaayah',
'nikayah',
'tanggallahir2',
'pendidikan1',
'pekerjaan1',
'penghasilan1',
'statusayah',
'statusibu',
'nikibu',
'tanggallahir3',
'pendidikan2',
'pekerjaan2',
'penghasilan2',
'namawali',
'nikwali',
'tanggallahir4',
'pendidikan3',
'pekerjaan3',
'penghasilan3',
'kontak',
'nomorwa',
'email',
'tinggibadan',
'beratbadan',
'jaraktempatkesekolah',
'jumlahsaudarakandung',
'asaltk',
'nomorsurattk',
'paktaintegritas',
'namaibu',
'status' ),
'exportFields' => array( 'ID',
'tanggaldaftar',
'nomap',
'namalengkap',
'jeniskelamin',
'nisn',
'nik',
'tempatlahir',
'tanggallahir1',
'noaktalahir',
'agama',
'alamatjalan',
'rt',
'rw',
'dusun',
'deskel',
'kecamatan',
'kodepos',
'tempattinggal',
'modatransportasi',
'anakke',
'namaayah',
'nikayah',
'tanggallahir2',
'pendidikan1',
'pekerjaan1',
'penghasilan1',
'statusayah',
'statusibu',
'nikibu',
'tanggallahir3',
'pendidikan2',
'pekerjaan2',
'penghasilan2',
'namawali',
'nikwali',
'tanggallahir4',
'pendidikan3',
'pekerjaan3',
'penghasilan3',
'kontak',
'nomorwa',
'email',
'tinggibadan',
'beratbadan',
'jaraktempatkesekolah',
'jumlahsaudarakandung',
'asaltk',
'nomorsurattk',
'paktaintegritas',
'namaibu',
'status' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'ID' => array( 'export_field' ),
'tanggaldaftar' => array( 'export_field1' ),
'nomap' => array( 'export_field2' ),
'namalengkap' => array( 'export_field3' ),
'jeniskelamin' => array( 'export_field4' ),
'nisn' => array( 'export_field5' ),
'nik' => array( 'export_field6' ),
'tempatlahir' => array( 'export_field7' ),
'tanggallahir1' => array( 'export_field8' ),
'noaktalahir' => array( 'export_field9' ),
'agama' => array( 'export_field10' ),
'alamatjalan' => array( 'export_field11' ),
'rt' => array( 'export_field12' ),
'rw' => array( 'export_field13' ),
'dusun' => array( 'export_field14' ),
'deskel' => array( 'export_field15' ),
'kecamatan' => array( 'export_field16' ),
'kodepos' => array( 'export_field17' ),
'tempattinggal' => array( 'export_field18' ),
'modatransportasi' => array( 'export_field19' ),
'anakke' => array( 'export_field20' ),
'namaayah' => array( 'export_field21' ),
'nikayah' => array( 'export_field22' ),
'tanggallahir2' => array( 'export_field23' ),
'pendidikan1' => array( 'export_field24' ),
'pekerjaan1' => array( 'export_field25' ),
'penghasilan1' => array( 'export_field26' ),
'statusayah' => array( 'export_field27' ),
'statusibu' => array( 'export_field28' ),
'nikibu' => array( 'export_field29' ),
'tanggallahir3' => array( 'export_field30' ),
'pendidikan2' => array( 'export_field31' ),
'pekerjaan2' => array( 'export_field32' ),
'penghasilan2' => array( 'export_field33' ),
'namawali' => array( 'export_field34' ),
'nikwali' => array( 'export_field35' ),
'tanggallahir4' => array( 'export_field36' ),
'pendidikan3' => array( 'export_field37' ),
'pekerjaan3' => array( 'export_field38' ),
'penghasilan3' => array( 'export_field39' ),
'kontak' => array( 'export_field40' ),
'nomorwa' => array( 'export_field41' ),
'email' => array( 'export_field42' ),
'tinggibadan' => array( 'export_field43' ),
'beratbadan' => array( 'export_field44' ),
'jaraktempatkesekolah' => array( 'export_field45' ),
'jumlahsaudarakandung' => array( 'export_field46' ),
'asaltk' => array( 'export_field47' ),
'nomorsurattk' => array( 'export_field48' ),
'paktaintegritas' => array( 'export_field49' ),
'namaibu' => array( 'export_field50' ),
'status' => array( 'export_field51' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'export_header' ),
'grid' => array( 'export_field',
'export_field1',
'export_field2',
'export_field3',
'export_field4',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field11',
'export_field12',
'export_field13',
'export_field14',
'export_field15',
'export_field16',
'export_field17',
'export_field18',
'export_field19',
'export_field20',
'export_field21',
'export_field22',
'export_field23',
'export_field24',
'export_field25',
'export_field26',
'export_field27',
'export_field28',
'export_field29',
'export_field30',
'export_field31',
'export_field32',
'export_field33',
'export_field34',
'export_field35',
'export_field36',
'export_field37',
'export_field38',
'export_field39',
'export_field40',
'export_field41',
'export_field42',
'export_field43',
'export_field44',
'export_field45',
'export_field46',
'export_field47',
'export_field48',
'export_field49',
'export_field50',
'export_field51' ),
'footer' => array( 'export_export',
'export_cancel' ) ),
'formXtTags' => array( 'supertop' => array(  ) ),
'itemForms' => array( 'export_header' => 'top',
'export_field' => 'grid',
'export_field1' => 'grid',
'export_field2' => 'grid',
'export_field3' => 'grid',
'export_field4' => 'grid',
'export_field5' => 'grid',
'export_field6' => 'grid',
'export_field7' => 'grid',
'export_field8' => 'grid',
'export_field9' => 'grid',
'export_field10' => 'grid',
'export_field11' => 'grid',
'export_field12' => 'grid',
'export_field13' => 'grid',
'export_field14' => 'grid',
'export_field15' => 'grid',
'export_field16' => 'grid',
'export_field17' => 'grid',
'export_field18' => 'grid',
'export_field19' => 'grid',
'export_field20' => 'grid',
'export_field21' => 'grid',
'export_field22' => 'grid',
'export_field23' => 'grid',
'export_field24' => 'grid',
'export_field25' => 'grid',
'export_field26' => 'grid',
'export_field27' => 'grid',
'export_field28' => 'grid',
'export_field29' => 'grid',
'export_field30' => 'grid',
'export_field31' => 'grid',
'export_field32' => 'grid',
'export_field33' => 'grid',
'export_field34' => 'grid',
'export_field35' => 'grid',
'export_field36' => 'grid',
'export_field37' => 'grid',
'export_field38' => 'grid',
'export_field39' => 'grid',
'export_field40' => 'grid',
'export_field41' => 'grid',
'export_field42' => 'grid',
'export_field43' => 'grid',
'export_field44' => 'grid',
'export_field45' => 'grid',
'export_field46' => 'grid',
'export_field47' => 'grid',
'export_field48' => 'grid',
'export_field49' => 'grid',
'export_field50' => 'grid',
'export_field51' => 'grid',
'export_export' => 'footer',
'export_cancel' => 'footer' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'export_header' => array( 'export_header' ),
'export_export' => array( 'export_export' ),
'export_cancel' => array( 'export_cancel' ),
'export_field' => array( 'export_field',
'export_field1',
'export_field2',
'export_field3',
'export_field4',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field11',
'export_field12',
'export_field13',
'export_field14',
'export_field15',
'export_field16',
'export_field17',
'export_field18',
'export_field19',
'export_field20',
'export_field21',
'export_field22',
'export_field23',
'export_field24',
'export_field25',
'export_field26',
'export_field27',
'export_field28',
'export_field29',
'export_field30',
'export_field31',
'export_field32',
'export_field33',
'export_field34',
'export_field35',
'export_field36',
'export_field37',
'export_field38',
'export_field39',
'export_field40',
'export_field41',
'export_field42',
'export_field43',
'export_field44',
'export_field45',
'export_field46',
'export_field47',
'export_field48',
'export_field49',
'export_field50',
'export_field51' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'export' => array( 'format' => 2,
'selectFields' => false,
'delimiter' => ',',
'selectDelimiter' => false,
'exportFileTypes' => array( 'excel' => true,
'word' => true,
'csv' => true,
'xml' => false ) ) );
			$pageArray = array( 'id' => 'export',
'type' => 'export',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'export-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_header' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'export-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_field',
'export_field1',
'export_field2',
'export_field3',
'export_field4',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field11',
'export_field12',
'export_field13',
'export_field14',
'export_field15',
'export_field16',
'export_field17',
'export_field18',
'export_field19',
'export_field20',
'export_field21',
'export_field22',
'export_field23',
'export_field24',
'export_field25',
'export_field26',
'export_field27',
'export_field28',
'export_field29',
'export_field30',
'export_field31',
'export_field32',
'export_field33',
'export_field34',
'export_field35',
'export_field36',
'export_field37',
'export_field38',
'export_field39',
'export_field40',
'export_field41',
'export_field42',
'export_field43',
'export_field44',
'export_field45',
'export_field46',
'export_field47',
'export_field48',
'export_field49',
'export_field50',
'export_field51' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'footer' => array( 'modelId' => 'export-footer',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c2' => array( 'model' => 'c2',
'items' => array( 'export_export',
'export_cancel' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'export_header' => array( 'type' => 'export_header' ),
'export_export' => array( 'type' => 'export_export' ),
'export_cancel' => array( 'type' => 'export_cancel' ),
'export_field' => array( 'field' => 'ID',
'type' => 'export_field' ),
'export_field1' => array( 'field' => 'tanggaldaftar',
'type' => 'export_field' ),
'export_field2' => array( 'field' => 'nomap',
'type' => 'export_field' ),
'export_field3' => array( 'field' => 'namalengkap',
'type' => 'export_field' ),
'export_field4' => array( 'field' => 'jeniskelamin',
'type' => 'export_field' ),
'export_field5' => array( 'field' => 'nisn',
'type' => 'export_field' ),
'export_field6' => array( 'field' => 'nik',
'type' => 'export_field' ),
'export_field7' => array( 'field' => 'tempatlahir',
'type' => 'export_field' ),
'export_field8' => array( 'field' => 'tanggallahir1',
'type' => 'export_field' ),
'export_field9' => array( 'field' => 'noaktalahir',
'type' => 'export_field' ),
'export_field10' => array( 'field' => 'agama',
'type' => 'export_field' ),
'export_field11' => array( 'field' => 'alamatjalan',
'type' => 'export_field' ),
'export_field12' => array( 'field' => 'rt',
'type' => 'export_field' ),
'export_field13' => array( 'field' => 'rw',
'type' => 'export_field' ),
'export_field14' => array( 'field' => 'dusun',
'type' => 'export_field' ),
'export_field15' => array( 'field' => 'deskel',
'type' => 'export_field' ),
'export_field16' => array( 'field' => 'kecamatan',
'type' => 'export_field' ),
'export_field17' => array( 'field' => 'kodepos',
'type' => 'export_field' ),
'export_field18' => array( 'field' => 'tempattinggal',
'type' => 'export_field' ),
'export_field19' => array( 'field' => 'modatransportasi',
'type' => 'export_field' ),
'export_field20' => array( 'field' => 'anakke',
'type' => 'export_field' ),
'export_field21' => array( 'field' => 'namaayah',
'type' => 'export_field' ),
'export_field22' => array( 'field' => 'nikayah',
'type' => 'export_field' ),
'export_field23' => array( 'field' => 'tanggallahir2',
'type' => 'export_field' ),
'export_field24' => array( 'field' => 'pendidikan1',
'type' => 'export_field' ),
'export_field25' => array( 'field' => 'pekerjaan1',
'type' => 'export_field' ),
'export_field26' => array( 'field' => 'penghasilan1',
'type' => 'export_field' ),
'export_field27' => array( 'field' => 'statusayah',
'type' => 'export_field' ),
'export_field28' => array( 'field' => 'statusibu',
'type' => 'export_field' ),
'export_field29' => array( 'field' => 'nikibu',
'type' => 'export_field' ),
'export_field30' => array( 'field' => 'tanggallahir3',
'type' => 'export_field' ),
'export_field31' => array( 'field' => 'pendidikan2',
'type' => 'export_field' ),
'export_field32' => array( 'field' => 'pekerjaan2',
'type' => 'export_field' ),
'export_field33' => array( 'field' => 'penghasilan2',
'type' => 'export_field' ),
'export_field34' => array( 'field' => 'namawali',
'type' => 'export_field' ),
'export_field35' => array( 'field' => 'nikwali',
'type' => 'export_field' ),
'export_field36' => array( 'field' => 'tanggallahir4',
'type' => 'export_field' ),
'export_field37' => array( 'field' => 'pendidikan3',
'type' => 'export_field' ),
'export_field38' => array( 'field' => 'pekerjaan3',
'type' => 'export_field' ),
'export_field39' => array( 'field' => 'penghasilan3',
'type' => 'export_field' ),
'export_field40' => array( 'field' => 'kontak',
'type' => 'export_field' ),
'export_field41' => array( 'field' => 'nomorwa',
'type' => 'export_field' ),
'export_field42' => array( 'field' => 'email',
'type' => 'export_field' ),
'export_field43' => array( 'field' => 'tinggibadan',
'type' => 'export_field' ),
'export_field44' => array( 'field' => 'beratbadan',
'type' => 'export_field' ),
'export_field45' => array( 'field' => 'jaraktempatkesekolah',
'type' => 'export_field' ),
'export_field46' => array( 'field' => 'jumlahsaudarakandung',
'type' => 'export_field' ),
'export_field47' => array( 'field' => 'asaltk',
'type' => 'export_field' ),
'export_field48' => array( 'field' => 'nomorsurattk',
'type' => 'export_field' ),
'export_field49' => array( 'field' => 'paktaintegritas',
'type' => 'export_field' ),
'export_field50' => array( 'field' => 'namaibu',
'type' => 'export_field' ),
'export_field51' => array( 'field' => 'status',
'type' => 'export_field' ) ),
'dbProps' => array(  ),
'version' => 4,
'exportFormat' => 2,
'exportDelimiter' => ',',
'exportSelectDelimiter' => false,
'exportSelectFields' => false );
		?>