<?php
$dalTablecalonppdb = array();
$dalTablecalonppdb["ID"] = array("type"=>3,"varname"=>"ID", "name" => "ID");
$dalTablecalonppdb["tanggaldaftar"] = array("type"=>200,"varname"=>"tanggaldaftar", "name" => "tanggaldaftar");
$dalTablecalonppdb["nomap"] = array("type"=>200,"varname"=>"nomap", "name" => "nomap");
$dalTablecalonppdb["namalengkap"] = array("type"=>200,"varname"=>"namalengkap", "name" => "namalengkap");
$dalTablecalonppdb["jeniskelamin"] = array("type"=>200,"varname"=>"jeniskelamin", "name" => "jeniskelamin");
$dalTablecalonppdb["nisn"] = array("type"=>200,"varname"=>"nisn", "name" => "nisn");
$dalTablecalonppdb["nik"] = array("type"=>200,"varname"=>"nik", "name" => "nik");
$dalTablecalonppdb["tempatlahir"] = array("type"=>200,"varname"=>"tempatlahir", "name" => "tempatlahir");
$dalTablecalonppdb["tanggallahir1"] = array("type"=>200,"varname"=>"tanggallahir1", "name" => "tanggallahir1");
$dalTablecalonppdb["noaktalahir"] = array("type"=>200,"varname"=>"noaktalahir", "name" => "noaktalahir");
$dalTablecalonppdb["agama"] = array("type"=>200,"varname"=>"agama", "name" => "agama");
$dalTablecalonppdb["alamatjalan"] = array("type"=>200,"varname"=>"alamatjalan", "name" => "alamatjalan");
$dalTablecalonppdb["rt"] = array("type"=>200,"varname"=>"rt", "name" => "rt");
$dalTablecalonppdb["rw"] = array("type"=>200,"varname"=>"rw", "name" => "rw");
$dalTablecalonppdb["dusun"] = array("type"=>200,"varname"=>"dusun", "name" => "dusun");
$dalTablecalonppdb["deskel"] = array("type"=>200,"varname"=>"deskel", "name" => "deskel");
$dalTablecalonppdb["kecamatan"] = array("type"=>200,"varname"=>"kecamatan", "name" => "kecamatan");
$dalTablecalonppdb["kodepos"] = array("type"=>200,"varname"=>"kodepos", "name" => "kodepos");
$dalTablecalonppdb["tempattinggal"] = array("type"=>200,"varname"=>"tempattinggal", "name" => "tempattinggal");
$dalTablecalonppdb["modatransportasi"] = array("type"=>200,"varname"=>"modatransportasi", "name" => "modatransportasi");
$dalTablecalonppdb["anakke"] = array("type"=>200,"varname"=>"anakke", "name" => "anakke");
$dalTablecalonppdb["namaayah"] = array("type"=>200,"varname"=>"namaayah", "name" => "namaayah");
$dalTablecalonppdb["nikayah"] = array("type"=>200,"varname"=>"nikayah", "name" => "nikayah");
$dalTablecalonppdb["tanggallahir2"] = array("type"=>200,"varname"=>"tanggallahir2", "name" => "tanggallahir2");
$dalTablecalonppdb["pendidikan1"] = array("type"=>200,"varname"=>"pendidikan1", "name" => "pendidikan1");
$dalTablecalonppdb["pekerjaan1"] = array("type"=>200,"varname"=>"pekerjaan1", "name" => "pekerjaan1");
$dalTablecalonppdb["penghasilan1"] = array("type"=>200,"varname"=>"penghasilan1", "name" => "penghasilan1");
$dalTablecalonppdb["statusayah"] = array("type"=>200,"varname"=>"statusayah", "name" => "statusayah");
$dalTablecalonppdb["statusibu"] = array("type"=>200,"varname"=>"statusibu", "name" => "statusibu");
$dalTablecalonppdb["nikibu"] = array("type"=>200,"varname"=>"nikibu", "name" => "nikibu");
$dalTablecalonppdb["tanggallahir3"] = array("type"=>200,"varname"=>"tanggallahir3", "name" => "tanggallahir3");
$dalTablecalonppdb["pendidikan2"] = array("type"=>200,"varname"=>"pendidikan2", "name" => "pendidikan2");
$dalTablecalonppdb["pekerjaan2"] = array("type"=>200,"varname"=>"pekerjaan2", "name" => "pekerjaan2");
$dalTablecalonppdb["penghasilan2"] = array("type"=>200,"varname"=>"penghasilan2", "name" => "penghasilan2");
$dalTablecalonppdb["namawali"] = array("type"=>200,"varname"=>"namawali", "name" => "namawali");
$dalTablecalonppdb["nikwali"] = array("type"=>200,"varname"=>"nikwali", "name" => "nikwali");
$dalTablecalonppdb["tanggallahir4"] = array("type"=>200,"varname"=>"tanggallahir4", "name" => "tanggallahir4");
$dalTablecalonppdb["pendidikan3"] = array("type"=>200,"varname"=>"pendidikan3", "name" => "pendidikan3");
$dalTablecalonppdb["pekerjaan3"] = array("type"=>200,"varname"=>"pekerjaan3", "name" => "pekerjaan3");
$dalTablecalonppdb["penghasilan3"] = array("type"=>200,"varname"=>"penghasilan3", "name" => "penghasilan3");
$dalTablecalonppdb["kontak"] = array("type"=>200,"varname"=>"kontak", "name" => "kontak");
$dalTablecalonppdb["nomorwa"] = array("type"=>200,"varname"=>"nomorwa", "name" => "nomorwa");
$dalTablecalonppdb["email"] = array("type"=>200,"varname"=>"email", "name" => "email");
$dalTablecalonppdb["tinggibadan"] = array("type"=>200,"varname"=>"tinggibadan", "name" => "tinggibadan");
$dalTablecalonppdb["beratbadan"] = array("type"=>200,"varname"=>"beratbadan", "name" => "beratbadan");
$dalTablecalonppdb["jaraktempatkesekolah"] = array("type"=>200,"varname"=>"jaraktempatkesekolah", "name" => "jaraktempatkesekolah");
$dalTablecalonppdb["jumlahsaudarakandung"] = array("type"=>200,"varname"=>"jumlahsaudarakandung", "name" => "jumlahsaudarakandung");
$dalTablecalonppdb["asaltk"] = array("type"=>200,"varname"=>"asaltk", "name" => "asaltk");
$dalTablecalonppdb["nomorsurattk"] = array("type"=>200,"varname"=>"nomorsurattk", "name" => "nomorsurattk");
$dalTablecalonppdb["paktaintegritas"] = array("type"=>200,"varname"=>"paktaintegritas", "name" => "paktaintegritas");
$dalTablecalonppdb["namaibu"] = array("type"=>200,"varname"=>"namaibu", "name" => "namaibu");
$dalTablecalonppdb["status"] = array("type"=>200,"varname"=>"status", "name" => "status");
	$dalTablecalonppdb["ID"]["key"]=true;

$dal_info["ppdb2022_at_localhost__calonppdb"] = &$dalTablecalonppdb;
?>